

-- ============================================================
-- FILE: supabase/sql/complete_supabase_schema.sql
-- ============================================================

-- =============================================================
-- SHIPLINK COMPLETE SUPABASE SCHEMA
-- Run this entire script in Supabase SQL Editor
-- =============================================================

-- 1. PROFILES (extends auth.users)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  first_name TEXT,
  last_name TEXT,
  name TEXT,
  phone_number TEXT,
  gender TEXT,
  address TEXT,
  code TEXT,
  role TEXT DEFAULT 'user',
  vehicle_number TEXT,
  state_id BIGINT,
  fcm_token TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Add missing columns safely (ignore if already exist)
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS code TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS vehicle_number TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS state_id BIGINT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS fcm_token TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS avatar_url TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS referred_by UUID;

-- RLS policies for profiles
DROP POLICY IF EXISTS "Users can insert own profile" ON profiles;
CREATE POLICY "Users can insert own profile" ON profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can view own profile" ON profiles;
CREATE POLICY "Users can view own profile" ON profiles
  FOR SELECT USING (auth.uid() = id OR auth.jwt()->>'role' = 'admin');

DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
CREATE POLICY "Users can update own profile" ON profiles
  FOR UPDATE USING (auth.uid() = id);

-- Allow drivers to view profiles of customers whose orders are assigned to them
DROP POLICY IF EXISTS "Drivers can view order customer profiles" ON profiles;
CREATE POLICY "Drivers can view order customer profiles" ON profiles
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM orders
      WHERE orders.user_id = profiles.id
      AND orders.driver_id = auth.uid()
    )
  );

-- 2. STATES (for driver regions)
CREATE TABLE IF NOT EXISTS states (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE states ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can read states" ON states;
CREATE POLICY "Anyone can read states" ON states
  FOR SELECT USING (true);

-- Insert some default states
INSERT INTO states (name) VALUES ('Cairo'), ('Alexandria'), ('Giza')
ON CONFLICT DO NOTHING;

-- Add FK from profiles.states after both tables exist (DO block avoids IF NOT EXISTS limitation)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'profiles_state_id_fkey'
  ) THEN
    ALTER TABLE profiles ADD CONSTRAINT profiles_state_id_fkey
      FOREIGN KEY (state_id) REFERENCES states(id);
  END IF;
END $$;

-- 3. PRODUCTS
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  image TEXT,
  images JSONB DEFAULT '[]'::jsonb,
  price NUMERIC(10,2),
  is_offer BOOLEAN DEFAULT false,
  new_price NUMERIC(10,2),
  qty INT DEFAULT 0,
  status INT DEFAULT 1,
  popular INT DEFAULT 0,
  provider_id BIGINT,
  is_top_seller BOOLEAN DEFAULT false,
  category TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Populate images JSONB for existing rows
UPDATE products SET images = jsonb_build_array(
  regexp_replace(image, 'thumbnail\\.webp$', '1.webp'),
  regexp_replace(image, 'thumbnail\\.webp$', '2.webp'),
  regexp_replace(image, 'thumbnail\\.webp$', '3.webp'),
  regexp_replace(image, 'thumbnail\\.webp$', '4.webp')
) WHERE images = '[]'::jsonb;

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can read products" ON products;
CREATE POLICY "Anyone can read products" ON products
  FOR SELECT USING (true);

-- 4. CART_ITEMS
CREATE TABLE IF NOT EXISTS cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity INT DEFAULT 1,
  cart_id BIGINT,
  total_price NUMERIC(10,2),
  is_open BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE cart_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage own cart" ON cart_items;
CREATE POLICY "Users can manage own cart" ON cart_items
  FOR ALL USING (auth.uid() = user_id);

-- 5. ORDERS
CREATE TABLE IF NOT EXISTS orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  cart_id BIGINT,
  total_price NUMERIC(10,2),
  order_code TEXT,
  status TEXT DEFAULT 'pending',
  driver_id UUID REFERENCES drivers(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Phase 1: delivery coordinates used by checkout / order_detail / driver app.
-- Idempotent: safe to re-run; does not alter existing data.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_address TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_lat DOUBLE PRECISION;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_lng DOUBLE PRECISION;

ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own orders" ON orders;
CREATE POLICY "Users can view own orders" ON orders
  FOR SELECT USING (auth.uid() = user_id OR auth.uid() = driver_id);

DROP POLICY IF EXISTS "Users can insert orders" ON orders;
CREATE POLICY "Users can insert orders" ON orders
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Drivers can update orders" ON orders;
CREATE POLICY "Drivers can update orders" ON orders
  FOR UPDATE
  USING (auth.uid() = driver_id OR driver_id IS NULL)
  WITH CHECK (auth.uid() = driver_id);

-- 6. DRIVERS (separate from profiles)
CREATE TABLE IF NOT EXISTS drivers (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name TEXT,
  email TEXT UNIQUE,
  phone_number TEXT UNIQUE,
  vehicle_type TEXT,
  vehicle_number TEXT,
  state TEXT,
  fcm_token TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE drivers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Drivers can insert own data" ON drivers;
CREATE POLICY "Drivers can insert own data"
  ON drivers FOR INSERT
  WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Drivers can view own data" ON drivers;
CREATE POLICY "Drivers can view own data"
  ON drivers FOR SELECT
  USING (auth.uid() = id);

DROP POLICY IF EXISTS "Drivers can update own data" ON drivers;
CREATE POLICY "Drivers can update own data"
  ON drivers FOR UPDATE
  USING (auth.uid() = id);

-- 7. DRIVER_LOCATIONS
CREATE TABLE IF NOT EXISTS driver_locations (
  driver_id UUID PRIMARY KEY REFERENCES drivers(id) ON DELETE CASCADE,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  status TEXT DEFAULT 'offline',
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE driver_locations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can read driver locations" ON driver_locations;
DROP POLICY IF EXISTS "Users can read driver locations" ON driver_locations;
CREATE POLICY "Users can read driver locations" ON driver_locations
  FOR SELECT USING (
    auth.uid() = driver_id OR
    EXISTS (
      SELECT 1 FROM orders
      WHERE orders.driver_id = driver_locations.driver_id
      AND orders.user_id = auth.uid()
      AND orders.status NOT IN ('delivered', 'cancelled')
    )
  );

DROP POLICY IF EXISTS "Drivers can update own location" ON driver_locations;
CREATE POLICY "Drivers can update own location" ON driver_locations
  FOR ALL USING (auth.uid() = driver_id) WITH CHECK (auth.uid() = driver_id);

-- 9. NOTIFICATIONS
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  driver_id UUID REFERENCES drivers(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  type TEXT DEFAULT 'general',
  read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  data JSONB
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own notifications" ON notifications;
CREATE POLICY "Users can view own notifications" ON notifications
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own notifications" ON notifications;
CREATE POLICY "Users can update own notifications" ON notifications
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert notifications" ON notifications;
CREATE POLICY "Users can insert notifications" ON notifications
  FOR INSERT WITH CHECK (
    auth.uid() = user_id
    OR EXISTS (SELECT 1 FROM drivers WHERE drivers.id = auth.uid())
  );

DROP POLICY IF EXISTS "Users can delete own notifications" ON notifications;

-- Notification preferences
CREATE TABLE IF NOT EXISTS notification_preferences (
  user_id UUID PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE,
  order_updates BOOLEAN DEFAULT true,
  chat_messages BOOLEAN DEFAULT true,
  promotions BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage own notification preferences" ON notification_preferences;
CREATE POLICY "Users can manage own notification preferences" ON notification_preferences
  FOR ALL USING (auth.uid() = user_id);

ALTER TABLE notification_preferences ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- 10. FAVOURITES
CREATE TABLE IF NOT EXISTS favourites (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, product_id)
);

ALTER TABLE favourites ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can manage own favourites" ON favourites;
CREATE POLICY "Users can manage own favourites" ON favourites
  FOR ALL USING (auth.uid() = user_id);

-- 11. SUPPORT_MESSAGES (user-admin chat)
CREATE TABLE IF NOT EXISTS support_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  sender_role TEXT DEFAULT 'user',
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE support_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own messages" ON support_messages;
CREATE POLICY "Users can view own messages" ON support_messages
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own messages" ON support_messages;
CREATE POLICY "Users can insert own messages" ON support_messages
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 12. PROMO_CODES
CREATE TABLE IF NOT EXISTS promo_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  discount_percent INT NOT NULL,
  max_uses INT DEFAULT 0,
  current_uses INT DEFAULT 0,
  expires_at TIMESTAMPTZ,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE promo_codes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Anyone can read promo_codes" ON promo_codes;
CREATE POLICY "Anyone can read promo_codes" ON promo_codes
  FOR SELECT USING (true);

-- 13. USER_ADDRESSES
CREATE TABLE IF NOT EXISTS user_addresses (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  label TEXT DEFAULT 'Home',
  city TEXT DEFAULT '',
  street TEXT DEFAULT '',
  building TEXT DEFAULT '',
  apartment TEXT DEFAULT '',
  full_address TEXT DEFAULT '',
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  is_default BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE user_addresses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "users_crud_own_addresses" ON user_addresses;
CREATE POLICY "users_crud_own_addresses"
  ON user_addresses
  FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Seed default promo codes
INSERT INTO promo_codes (code, discount_percent, max_uses) VALUES
  ('SAVE10', 10, 100),
  ('SAVE20', 20, 50),
  ('WELCOME5', 5, 200)
ON CONFLICT (code) DO NOTHING;

-- =============================================================
-- NEW TABLES for v2 features (order_items, reviews, driver_ratings, order_chat_messages)
-- =============================================================

-- 14. ORDER_ITEMS (line items per order, for "Order Again")
CREATE TABLE IF NOT EXISTS order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity INT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own order items" ON order_items;
CREATE POLICY "Users can view own order items"
  ON order_items FOR SELECT
  USING (
    order_id IN (SELECT id FROM orders WHERE user_id = auth.uid())
  );

DROP POLICY IF EXISTS "Users can insert own order items" ON order_items;
CREATE POLICY "Users can insert own order items"
  ON order_items FOR INSERT
  WITH CHECK (
    order_id IN (SELECT id FROM orders WHERE user_id = auth.uid())
  );

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);

-- 15. REVIEWS (product reviews by users)
CREATE TABLE IF NOT EXISTS reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  order_id BIGINT REFERENCES orders(id) ON DELETE SET NULL,
  rating SMALLINT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view reviews" ON reviews;
CREATE POLICY "Anyone can view reviews"
  ON reviews FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users can insert own reviews" ON reviews;
CREATE POLICY "Users can insert own reviews"
  ON reviews FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own reviews" ON reviews;
CREATE POLICY "Users can update own reviews"
  ON reviews FOR UPDATE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own reviews" ON reviews;
CREATE POLICY "Users can delete own reviews"
  ON reviews FOR DELETE
  USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user_id ON reviews(user_id);

-- 16. DRIVER_RATINGS (user rates driver after delivery)
CREATE TABLE IF NOT EXISTS driver_ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  driver_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  rating SMALLINT NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE driver_ratings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view driver ratings" ON driver_ratings;
CREATE POLICY "Anyone can view driver ratings"
  ON driver_ratings FOR SELECT
  USING (true);

DROP POLICY IF EXISTS "Users can insert own driver ratings" ON driver_ratings;
CREATE POLICY "Users can insert own driver ratings"
  ON driver_ratings FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_driver_ratings_driver_id ON driver_ratings(driver_id);
CREATE INDEX IF NOT EXISTS idx_driver_ratings_order_id ON driver_ratings(order_id);

-- 17. ORDER_CHAT_MESSAGES (real-time chat between user and driver)
CREATE TABLE IF NOT EXISTS order_chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  sender_role TEXT NOT NULL CHECK (sender_role IN ('user', 'driver')),
  message TEXT NOT NULL,
  read BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE order_chat_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Participants can view chat messages" ON order_chat_messages;
CREATE POLICY "Participants can view chat messages"
  ON order_chat_messages FOR SELECT
  USING (
    sender_id = auth.uid()
    OR order_id IN (
      SELECT id FROM orders WHERE user_id = auth.uid() OR driver_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Participants can insert messages" ON order_chat_messages;
CREATE POLICY "Participants can insert messages"
  ON order_chat_messages FOR INSERT
  WITH CHECK (
    sender_id = auth.uid()
    AND order_id IN (
      SELECT id FROM orders WHERE user_id = auth.uid() OR driver_id = auth.uid()
    )
  );

CREATE INDEX IF NOT EXISTS idx_order_chat_order_id ON order_chat_messages(order_id);
CREATE INDEX IF NOT EXISTS idx_order_chat_created_at ON order_chat_messages(created_at);

-- Enable Realtime for order_chat_messages and notifications
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'order_chat_messages'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.order_chat_messages;
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'notifications'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
  END IF;
END $$;

-- Add data column to notifications for existing installations
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS data JSONB;

-- Auto-delete chat messages when order is delivered
CREATE OR REPLACE FUNCTION delete_chat_on_delivery()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.status = 'delivered' AND OLD.status <> 'delivered' THEN
    DELETE FROM order_chat_messages WHERE order_id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_delete_chat_on_delivery ON orders;
CREATE TRIGGER trg_delete_chat_on_delivery
  AFTER UPDATE OF status ON orders
  FOR EACH ROW
  EXECUTE FUNCTION delete_chat_on_delivery();

-- ============================================================
-- Execute this SQL in Supabase SQL Editor to fix the error
-- ============================================================
-- Drop the problematic trigger first
DROP TRIGGER IF EXISTS trg_orders_updated_at ON orders;
DROP FUNCTION IF EXISTS update_updated_at();

-- Add updated_at column if it doesn't exist
ALTER TABLE orders ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now();

-- Recreate the function and trigger
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_orders_updated_at ON orders;
CREATE TRIGGER trg_orders_updated_at
  BEFORE UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();



-- ============================================================
-- FILE: supabase/migrations/20260629191000_add_paymob_columns.sql
-- ============================================================

ALTER TABLE orders ADD COLUMN IF NOT EXISTS paymob_order_id BIGINT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ;
CREATE INDEX IF NOT EXISTS idx_orders_paymob_order_id ON orders(paymob_order_id);



-- ============================================================
-- FILE: supabase/migrations/20260702121000_add_delete_rls_policies.sql
-- ============================================================

DROP POLICY IF EXISTS "Users can delete own notifications" ON notifications;
CREATE POLICY "Users can delete own notifications"
  ON notifications FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own support messages" ON support_messages;
CREATE POLICY "Users can delete own support messages"
  ON support_messages FOR DELETE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Participants can delete own messages" ON order_chat_messages;
CREATE POLICY "Participants can delete own messages"
  ON order_chat_messages FOR DELETE
  USING (sender_id = auth.uid());



-- ============================================================
-- FILE: supabase/migrations/20260705120000_add_delivery_instructions.sql
-- ============================================================

    ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_instructions TEXT DEFAULT '';



-- ============================================================
-- FILE: supabase/migrations/20260705130000_create_stock_watch.sql
-- ============================================================

CREATE TABLE IF NOT EXISTS stock_watch (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  notified BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, product_id)
);

ALTER TABLE stock_watch ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own watches" ON stock_watch;
CREATE POLICY "Users can view own watches" ON stock_watch
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own watches" ON stock_watch;
CREATE POLICY "Users can insert own watches" ON stock_watch
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own watches" ON stock_watch;
CREATE POLICY "Users can update own watches" ON stock_watch
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own watches" ON stock_watch;
CREATE POLICY "Users can delete own watches" ON stock_watch
  FOR DELETE USING (auth.uid() = user_id);



-- ============================================================
-- FILE: supabase/migrations/20260705140000_add_unique_email_phone.sql
-- ============================================================

-- Add UNIQUE constraints on profiles.email and profiles.phone_number
-- Nullify duplicates instead of deleting (avoids cascading data loss)
UPDATE profiles SET email = NULL WHERE id IN (
  SELECT id FROM (
    SELECT id, ROW_NUMBER() OVER (
      PARTITION BY email ORDER BY created_at DESC NULLS LAST
    ) AS rn
    FROM profiles WHERE email IS NOT NULL
  ) dup WHERE rn > 1
);
UPDATE profiles SET phone_number = NULL WHERE id IN (
  SELECT id FROM (
    SELECT id, ROW_NUMBER() OVER (
      PARTITION BY phone_number ORDER BY created_at DESC NULLS LAST
    ) AS rn
    FROM profiles WHERE phone_number IS NOT NULL AND phone_number != ''
  ) dup WHERE rn > 1
);
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'profiles_email_key') THEN
    ALTER TABLE profiles ADD CONSTRAINT profiles_email_key UNIQUE (email);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'profiles_phone_number_key') THEN
    ALTER TABLE profiles ADD CONSTRAINT profiles_phone_number_key UNIQUE (phone_number);
  END IF;
END $$;



-- ============================================================
-- FILE: supabase/migrations/20260825000000_add_order_delivery_coords.sql
-- ============================================================

-- Phase 1: add delivery coordinates to the orders table.
-- These columns are already written by checkout (cart_repository_impl) and
-- read by order_detail / driver orders_map, but were missing from the schema.
-- Idempotent and non-destructive.
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_address TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_lat DOUBLE PRECISION;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_lng DOUBLE PRECISION;



-- ============================================================
-- FILE: supabase/migrations/20260829000000_add_rls_indexes.sql
-- ============================================================

-- Phase 7: performance indexes for RLS evaluation and notification polling.
-- Safe / idempotent; non-destructive.

CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders (user_id);
CREATE INDEX IF NOT EXISTS idx_orders_driver_id ON orders (driver_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications (user_id);



-- ============================================================
-- FILE: supabase/migrations/20260829000001_add_push_sent.sql
-- ============================================================

-- Phase 8: add push_sent flag to notifications so send_push can record delivery status.
-- Non-destructive / idempotent.

ALTER TABLE notifications
  ADD COLUMN IF NOT EXISTS push_sent BOOLEAN NOT NULL DEFAULT false;



-- ============================================================
-- FILE: supabase/migrations/20260829000002_add_driver_location_telemetry.sql
-- ============================================================

-- QA BUG-001: promote driver_locations telemetry columns into a versioned
-- migration so Supabase auto-applies it. Previously only in the ad-hoc
-- supabase/sql/phase5_driver_locations.sql, which Supabase does NOT run
-- automatically. driver_tracking_session.dart upserts heading/speed/accuracy/
-- last_seen/is_online, so these columns must exist on the live DB or live
-- tracking writes fail.

ALTER TABLE driver_locations
  ADD COLUMN IF NOT EXISTS heading DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS speed DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS accuracy DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS last_seen TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS is_online BOOLEAN DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS driver_locations_last_seen_idx
  ON driver_locations (last_seen);

CREATE INDEX IF NOT EXISTS driver_locations_updated_at_idx
  ON driver_locations (updated_at);



-- ============================================================
-- FILE: supabase/migrations/20260829000003_tighten_notifications_insert_rls.sql
-- ============================================================

-- QA BUG-002: tighten notifications INSERT RLS. The client inserts
-- notifications with user_id = recipient (e.g. driver -> customer), so a naive
-- "auth.uid() = user_id" check would break that flow. Instead allow the
-- recipient themselves, or any driver, to create notifications. This blocks a
-- customer from forging notifications for *another* customer while preserving
-- the legitimate driver -> customer path. Server/edge inserts use service_role
-- and bypass RLS entirely.

DROP POLICY IF EXISTS "Users can insert notifications" ON notifications;
DROP POLICY IF EXISTS "service_insert_notifications" ON notifications;

DROP POLICY IF EXISTS "Users can insert notifications" ON notifications;
CREATE POLICY "Users can insert notifications" ON notifications
  FOR INSERT WITH CHECK (
    auth.uid() = user_id
    OR EXISTS (SELECT 1 FROM drivers WHERE drivers.id = auth.uid())
  );



-- ============================================================
-- FILE: supabase/migrations/payment_methods.sql
-- ============================================================

-- Payment Methods table for saved cards
CREATE TABLE IF NOT EXISTS payment_methods (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  paymob_token TEXT NOT NULL,
  last_four TEXT NOT NULL,
  card_brand TEXT DEFAULT '',
  is_default BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- RLS
ALTER TABLE payment_methods ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own payment methods"
  ON payment_methods FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own payment methods"
  ON payment_methods FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own payment methods"
  ON payment_methods FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own payment methods"
  ON payment_methods FOR DELETE
  USING (auth.uid() = user_id);


