CREATE TABLE IF NOT EXISTS order_chat_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  sender_role TEXT NOT NULL CHECK (sender_role IN ('user', 'driver')),
  message TEXT NOT NULL,
  read BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE order_chat_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Participants can view chat messages"
  ON order_chat_messages FOR SELECT
  USING (
    sender_id = auth.uid()
    OR order_id IN (
      SELECT id FROM orders WHERE user_id = auth.uid() OR driver_id = auth.uid()
    )
  );

CREATE POLICY "Participants can insert messages"
  ON order_chat_messages FOR INSERT
  WITH CHECK (
    sender_id = auth.uid()
    AND order_id IN (
      SELECT id FROM orders WHERE user_id = auth.uid() OR driver_id = auth.uid()
    )
  );

CREATE INDEX IF NOT EXISTS idx_order_chat_order_id ON order_chat_messages(order_id);
CREATE INDEX IF NOT EXISTS idx_order_chat_created_at ON order_chat_messages(created_at);
