import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'ShipLink',
      'ship_link': 'Ship Link',
      'home': 'Home',
      'search': 'Search',
      'cart': 'Cart',
      'profile': 'Profile',
      'my_profile': 'My Profile',
      'orders': 'Orders',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'sign_out': 'Sign Out',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'shipments': 'Shipments',
      'track_shipment': 'Track Shipment',
      'delivery_address': 'Delivery Address',
      'payment': 'Payment',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'top_sellers': 'Best Seller',
      'all_products': 'All Products',
      'add_to_cart': 'Add to Cart',
      'checkout': 'Checkout',
      'total': 'Total',
      'subtotal': 'Subtotal',
      'discount': 'Discount',
      'original_price': 'Original Price',
      'driver_mode': 'Driver Mode',
      'accept_order': 'Accept Order',
      'live_tracking': 'Live Tracking',
      'settings': 'Settings',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'orders_history': 'Orders History',
      'my_orders': 'My Orders',
      'pending': 'Pending',
      'shipped': 'Shipped',
      'in_transit': 'In Transit',
      'delivered': 'Delivered',
      'cancelled': 'Cancelled',
      'account_settings': 'Account Settings',
      'personal_information': 'Personal Information',
      'address_book': 'Address Book',
      'payment_methods': 'Payment Methods',
      'notifications': 'Notifications',
      'notification_preferences': 'Notification Preferences',
      'order_updates': 'Order Updates',
      'chat_messages': 'Chat Messages',
      'promotions': 'Promotions',
      'you_may_also_like': 'You May Also Like',
      'choose_from_gallery': 'Choose from gallery',
      'take_a_photo': 'Take a photo',
      'referral_code': 'Referral Code',
      'share_code_description': 'Share your code with friends and earn rewards!',
      'download_invoice': 'Download Invoice',
      'mute_notifications': 'Mute Notifications',
      'unmute_notifications': 'Unmute Notifications',
      'notifications_muted_for_order': 'Notifications muted for this order',
      'notifications_unmuted_for_order': 'Notifications unmuted for this order',
      'earnings_overview': 'Earnings Overview',
      'order_status_distribution': 'Order Status Distribution',
      'my_chats': 'My Chats',
      'security': 'Security',
      'support': 'Support',
      'help_center': 'Help Center',
      'contact_us': 'Contact Us',
      'about_shiplink': 'About ShipLink',
      'log_out': 'Log Out',
      'save_changes': 'Save Changes',
      'edit_profile': 'Edit Profile',
      'add_address': 'Add Address',
      'edit_address': 'Edit Address',
      'save_address': 'Save Address',
      'update_address': 'Update Address',
      'pick_from_maps': 'Pick from Google Maps',
      'confirm_location': 'Confirm Location',
      'default_address': 'Default',
      'set_as_default': 'Set as Default',
      'delete': 'Delete',
      'edit': 'Edit',
      'no_addresses': 'No addresses saved yet',
      'tap_add_address': 'Tap + to add a new address',
      'label': 'Label',
      'city': 'City',
      'street': 'Street',
      'building': 'Building',
      'apartment': 'Apartment',
      'full_address': 'Full Address',
      'enter_address_manually': 'Enter address manually or use Google Maps',
      'apt': 'Apt',
      'no_favourites': 'No favourites yet',
      'tap_heart_to_save': 'Tap the heart on any product to save it here',
      'your_cart_is_empty': 'Your cart is empty',
      'not_added_anything_yet': 'Not added anything yet',
      'start_shopping': 'Start Shopping',
      'promo_code': 'Promo Code',
      'apply': 'Apply',
      'percent_off_applied': '% off applied!',
      'invalid_promo_code': 'Invalid promo code',
      'search_products': 'Search products...',
      'search_for_products': 'Search for products',
      'categories': 'Categories',
      'filtered_products': 'Filtered Products',
      'clear_filter': 'Clear',
      'view_all': 'View All',
      'all': 'All',
      'quantity': 'Quantity',
      'added_to_cart': 'Added to cart',
      'removed_from_cart': 'Removed from cart',
      'item_removed_from_cart': 'removed from cart',
      'proceed_to_checkout': 'Proceed to Checkout',
      'order_history': 'Order History',
      'order_code': 'Your Order Code:',
      'reward_points': 'Reward Points',
      'two_factor_auth': 'Two-Factor Authentication',
      'change_password': 'Change Password',
      'active_sessions': 'Active Sessions',
      'security_tips': 'Tips to keep your account secure',
      'security_settings': 'Security Settings',
      'tip_strong_password': 'Use a strong, unique password',
      'tip_enable_2fa': 'Enable two-factor authentication',
      'tip_review_sessions': 'Review active sessions regularly',
      'english': 'English',
      'arabic': 'العربية',
      'browse': 'BROWSE',
      'logout': 'Logout',
      'logout_confirm_title': 'Log Out',
      'are_you_sure_logout': 'Are you sure you want to log out?',
      'logout_successful': 'Logout Successful',
      'top_categories': 'Top Categories',
      'top_seller_products': 'Top Seller Products',
      'my_favourites': 'My Favourites',
      'product_not_found': 'Product not found',
      'my_cart': 'My Cart',
      'no_products_found': 'No products found',
      'could_not_load_products': 'Could not load products',
      'retry': 'Retry',
      'category': 'Category',
      'explore': 'Explore',
      'developed_by': 'Developed by MahmoudFahmy \u00a9 2023',
      'special_offer': 'Special Offer',
      'up_to_off': 'Up to % OFF',
      'shop_now': 'Shop Now',
      'lets_go': "Let's Go",
      'get_special_discount': 'Get Special Discount\n',
      'offer_up_to': 'Up to  ',
      'no_notifications_yet': 'No notifications yet',
      'mark_read': 'Mark read',
      'driver_location': 'Driver Location',
      'deliverd': 'Delivered',
      'processing': 'Processing',
      'canceled': 'Canceled',
      'no_orders_yet': 'No orders yet',
      'no_orders_hint': 'Your orders will appear here after checkout',
      'detail': 'Detail',
      'total_amount': 'Total Amount:  ',
      'order_no': 'Order No',
      'email_address': 'Email Address',
      'edit_your_personal_details': 'Edit your personal details',
      'profile_updated_successfully': 'Profile updated successfully',
      'name_required': 'Name is required',
      'valid_email_required': 'Valid email is required',
      'email_already_in_use': 'This email is already in use by another account',
      'phone_already_in_use': 'This phone number is already in use by another account',
      'success': 'SUCCESS!',
      'order_will_be_delivered': 'Your order will be delivered soon.\n',
      'thank_you': 'Thank you for choosing our app!',
      'track_your_orders': 'Track your orders',
      'back_to_home': 'Back To Home',
      'unknown_error': 'Unknown Error,Please try again later ',
      'share_feature_coming_soon': 'Share feature coming soon',
      'order_subtotal': 'Order Subtotal:',
      'discount_percent': 'Discount (%d%%):',
      'total_colon': 'Total:',
      'something_error': 'something error',
      'error': 'Error',
      'registration_failed': 'Registration failed',
      'create_account': 'Create Account',
      'create_account_subtitle': 'Create your account to get started.',
      'sign_up_as': 'SignUp as:',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'first_name_required': 'first name is required',
      'last_name_required': 'last name is required',
      'name_must_be_more_than_2': 'Name must be more than 2 characters',
      'enter_first_name': 'Enter Your First Name',
      'enter_last_name': 'Enter Your Last Name',
      'please_enter_email': 'Please enter an email address',
      'please_enter_valid_email': 'Please enter a valid email address',
      'enter_email': 'Enter Your Email',
      'phone_number_optional': 'Phone Number (Optional)',
      'enter_phone': 'Enter Your Phone Number',
      'address': 'Address',
      'address_required': 'address is required',
      'address_detailed': 'address must be more accurate and detailed',
      'enter_address': 'Enter Your Address',
      'postal_code': 'Postal Code',
      'enter_postal_code': 'Enter Your Postal Code',
      'password_required': 'Password is required',
      'password_min_length': 'Password must be at least 6 characters',
      'password_complexity': 'Password should contain upper, lower, digit and Special character',
      'enter_password': 'Enter Your Password',
      'confirm_password': 'Confirm Password',
      'confirm_your_password': 'Confirm your password',
      'please_confirm_password': 'Please confirm your password',
      'passwords_do_not_match': 'Passwords do not match',
      'empty': 'Empty',
      'not_match': 'Not Match',
      'enter_confirm_password': 'Enter Your Confirm Password',
      'i_already_have_account': 'I already have an account!',
      'i_agree_terms': 'I agree to the Terms of Service and Privacy Policy',
      'please_agree_terms': 'Please agree to the Terms of Service',
      'already_have_account': 'Already have an account? ',
      'register': 'Register',
      'creating_account': 'Creating Account...',
      'username': 'Username',
      'enter_username': 'Enter your username',
      'username_required': 'Username is required',
      'username_min_length': 'Username must be at least 3 characters',
      'forgot_password': 'Forgot Password?',
      'forgot_password_title': 'Forgot Password!',
      'forgot_password_subtitle': "Don't worry! It happens. Please enter the phone number we will send the OTP to.",
      'enter_phone_number': 'Enter the phone number',
      'continue_btn': 'Continue',
      'verification': 'Verification',
      'otp_verification': 'OTP VERIFICATION',
      'enter_otp': 'Enter the OTP sent to ',
      'dont_receive_code': "Don't receive code? ",
      'resend': 'Re-send',
      'submit': 'Submit',
      'password_update_success': 'Password Update \nSuccessfully',
      'password_updated_message': 'your password has been \nupdated successfully',
      'sec': ' Sec',
      'reset_password': 'Reset Password',
      'reset_password_subtitle': "Enter your email address and we'll send you a link to reset your password.",
      'send_reset_link': 'Send Reset Link',
      'remember_password': 'Remember your password? ',
      'login': 'Login',
      'check_inbox': 'Please check your inbox and spam folder.',
      'failed_send_reset': 'Failed to send reset link',
      'signing_in': 'Signing In...',
      'email_or_password_incorrect': 'Email or Password Incorrect',
      'welcome_back_title': 'Welcome Back!',
      'welcome_back_subtitle': 'welcome back we missed you',
      'first_time_here': 'First time here? ',
      'signup': 'SignUp ',
      'or_continue_with': 'Or continue with',
      'google': 'Google',
      'apple': 'Apple',
      'welcome_to_shopease': 'Welcome to ShopEase',
      'discover_best_products': 'Discover the best products with fast and reliable delivery.',
      'by_continuing_agree': 'By continuing, you agree to our Terms of Service and Privacy Policy',
      'shop': 'Shop',
      'ease': 'Ease',
      'your_delivery_partner': 'Your delivery partner',
      'welcome_back': 'Welcome Back',
      'sign_in_to_continue': 'Sign in to continue',
      'fill_details': 'Fill in the details to get started',
      'payment_successful': 'Payment Successful',
      'payment_failed': 'Payment Failed',
      'press_back_again_exit': 'Press back again to exit',
      'pick_location': 'Pick Location',
      'tap_map_to_set': 'Tap on the map to set your delivery location',
      'set_your_location': 'Set Your Location',
      'save_and_continue': 'Save & Continue',
      'not_added_anything': 'Not added anything yet',
      'review_count': '(%d reviews)',
      'login_title': 'LOGIN',
      'login_subtitle': 'Enter your credentials to access your account',
      'sign_up_user': 'Sign UP User ',
      'email_required': 'Email is required',
      'valid_email': 'Enter a valid email address',
      'dont_have_account': "Don't have an account? ",
      'password_required_field': 'Password is required',
      'first_name_required_field': 'first name is required',
      'app_bar_search': 'Search',
      'home_drawer': 'Home',
      'favourites_drawer': 'Favourites',
      'profile_drawer': 'Profile',
      'log_out_drawer': 'Logout',
      'online': 'Online',
      'today': 'Today',
      'connecting_deliveries': 'Connecting Deliveries...',
      'fast_shipping_low_costs': 'Fast Shipping at Low\nCosts',
      'exit': 'Exit',
      'driver_management': 'Driver Management',
      'driver_management_soon': 'Driver management coming soon',
      'edit_user_info': 'Edit User Info',
      'button_text': 'Button',
      'accepted_orders': 'Accepted Orders',
      'your_state': 'Your State',
      'order_details': 'Order Details',
      'items': 'Items',
      'product': 'Product',
      'order_date': 'Order Date',
      'order_status': 'Order Status',
      'cancel_order': 'Cancel Order',
      'cancel_order_confirm': 'Are you sure you want to cancel this order?',
      'order_cancelled': 'Order cancelled successfully',
      'yes': 'Yes',
      'no': 'No',
      'reviews': 'Reviews',
      'write_review': 'Write a Review',
      'review_hint': 'Share your thoughts about this product...',
      'no_reviews_yet': 'No reviews yet',
      'rate_driver': 'Rate Driver',
      'driver_rated': 'Driver rated',
      'chat_with_driver': 'Chat with Driver',
      'min_price': 'Min price',
      'max_price': 'Max price',
      'order_again': 'Order Again',
      'items_added_to_cart': 'Items added to cart',
    },
    'ar': {
      'app_name': 'ShipLink',
      'ship_link': 'Ship Link',
      'home': 'الرئيسية',
      'search': 'بحث',
      'cart': 'السلة',
      'profile': 'الملف الشخصي',
      'my_profile': 'ملفي الشخصي',
      'orders': 'الطلبات',
      'sign_in': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'sign_out': 'تسجيل الخروج',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'name': 'الاسم',
      'full_name': 'الاسم الكامل',
      'phone_number': 'رقم الهاتف',
      'shipments': 'الشحنات',
      'track_shipment': 'تتبع الشحنة',
      'delivery_address': 'عنوان التوصيل',
      'payment': 'الدفع',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'top_sellers': 'الأكثر مبيعاً',
      'all_products': 'جميع المنتجات',
      'add_to_cart': 'أضف إلى السلة',
      'checkout': 'إتمام الشراء',
      'total': 'الإجمالي',
      'subtotal': 'المجموع الفرعي',
      'discount': 'الخصم',
      'original_price': 'السعر الأصلي',
      'driver_mode': 'وضع السائق',
      'accept_order': 'قبول الطلب',
      'live_tracking': 'تتبع مباشر',
      'settings': 'الإعدادات',
      'dark_mode': 'الوضع الليلي',
      'language': 'اللغة',
      'orders_history': 'سجل الطلبات',
      'my_orders': 'طلباتي',
      'pending': 'قيد الانتظار',
      'shipped': 'تم الشحن',
      'in_transit': 'قيد التوصيل',
      'delivered': 'تم التوصيل',
      'cancelled': 'ملغي',
      'account_settings': 'إعدادات الحساب',
      'personal_information': 'المعلومات الشخصية',
      'address_book': 'دفتر العناوين',
      'payment_methods': 'طرق الدفع',
      'notifications': 'الإشعارات',
      'notification_preferences': 'إعدادات الإشعارات',
      'order_updates': 'تحديثات الطلبات',
      'chat_messages': 'رسائل المحادثة',
      'promotions': 'العروض',
      'you_may_also_like': 'قد يعجبك أيضاً',
      'choose_from_gallery': 'اختر من المعرض',
      'take_a_photo': 'التقاط صورة',
      'referral_code': 'كود الإحالة',
      'share_code_description': 'شارك الكود مع أصدقائك واكسب المكافآت!',
      'download_invoice': 'تنزيل الفاتورة',
      'mute_notifications': 'كتم الإشعارات',
      'unmute_notifications': 'إلغاء كتم الإشعارات',
      'notifications_muted_for_order': 'تم كتم الإشعارات لهذا الطلب',
      'notifications_unmuted_for_order': 'تم إلغاء كتم الإشعارات لهذا الطلب',
      'earnings_overview': 'نظرة عامة على الأرباح',
      'order_status_distribution': 'توزيع حالات الطلبات',
      'my_chats': 'محادثاتي',
      'security': 'الأمان',
      'support': 'الدعم',
      'help_center': 'مركز المساعدة',
      'contact_us': 'اتصل بنا',
      'about_shiplink': 'عن ShipLink',
      'log_out': 'تسجيل الخروج',
      'save_changes': 'حفظ التغييرات',
      'edit_profile': 'تعديل الملف الشخصي',
      'add_address': 'إضافة عنوان',
      'edit_address': 'تعديل العنوان',
      'save_address': 'حفظ العنوان',
      'update_address': 'تحديث العنوان',
      'pick_from_maps': 'اختيار من خرائط جوجل',
      'confirm_location': 'تأكيد الموقع',
      'default_address': 'افتراضي',
      'set_as_default': 'تعيين كافتراضي',
      'delete': 'حذف',
      'edit': 'تعديل',
      'no_addresses': 'لا توجد عناوين محفوظة',
      'tap_add_address': 'اضغط + لإضافة عنوان جديد',
      'label': 'تسمية',
      'city': 'المدينة',
      'street': 'الشارع',
      'building': 'المبنى',
      'apartment': 'الشقة',
      'full_address': 'العنوان الكامل',
      'enter_address_manually': 'أدخل العنوان يدوياً أو استخدم خرائط جوجل',
      'apt': 'شقة',
      'no_favourites': 'لا توجد مفضلات',
      'tap_heart_to_save': 'اضغط على القلب على أي منتج لحفظه هنا',
      'your_cart_is_empty': 'سلتك فارغة',
      'not_added_anything_yet': 'لم تضف أي شيء بعد',
      'start_shopping': 'ابدأ التسوق',
      'promo_code': 'كود الخصم',
      'apply': 'تطبيق',
      'percent_off_applied': '% خصم مطبق!',
      'invalid_promo_code': 'كود خصم غير صالح',
      'search_products': 'ابحث عن منتجات...',
      'search_for_products': 'ابحث عن منتجات',
      'categories': 'التصنيفات',
      'filtered_products': 'المنتجات المفلترة',
      'clear_filter': 'مسح',
      'view_all': 'عرض الكل',
      'all': 'الكل',
      'quantity': 'الكمية',
      'added_to_cart': 'تمت الإضافة إلى السلة',
      'removed_from_cart': 'تمت الإزالة من السلة',
      'item_removed_from_cart': 'تمت الإزالة من السلة',
      'proceed_to_checkout': 'المتابعة للدفع',
      'order_history': 'سجل الطلبات',
      'order_code': 'رمز طلبك:',
      'reward_points': 'نقاط المكافآت',
      'two_factor_auth': 'التحقق بخطوتين',
      'change_password': 'تغيير كلمة المرور',
      'active_sessions': 'الجلسات النشطة',
      'security_tips': 'نصائح للحفاظ على أمان حسابك',
      'security_settings': 'إعدادات الأمان',
      'tip_strong_password': 'استخدم كلمة مرور قوية وفريدة',
      'tip_enable_2fa': 'فعّل التحقق بخطوتين',
      'tip_review_sessions': 'راجع الجلسات النشطة بانتظام',
      'english': 'English',
      'arabic': 'العربية',
      'browse': 'تصفح',
      'logout': 'تسجيل الخروج',
      'logout_confirm_title': 'تسجيل الخروج',
      'are_you_sure_logout': 'هل أنت متأكد من تسجيل الخروج؟',
      'logout_successful': 'تم تسجيل الخروج بنجاح',
      'top_categories': 'أفضل التصنيفات',
      'top_seller_products': 'الأكثر مبيعاً',
      'my_favourites': 'مفضلتي',
      'product_not_found': 'المنتج غير موجود',
      'my_cart': 'سلتي',
      'no_products_found': 'لا توجد منتجات',
      'could_not_load_products': 'تعذر تحميل المنتجات',
      'retry': 'إعادة المحاولة',
      'category': 'التصنيفات',
      'explore': 'استكشاف',
      'developed_by': 'طور بواسطة MahmoudFahmy \u00a9 2023',
      'special_offer': 'عرض خاص',
      'up_to_off': 'خصم يصل إلى %',
      'shop_now': 'تسوق الآن',
      'lets_go': 'هيا بنا',
      'get_special_discount': 'احصل على خصم خاص\n',
      'offer_up_to': 'يصل إلى  ',
      'no_notifications_yet': 'لا توجد إشعارات',
      'mark_read': 'تم القراءة',
      'driver_location': 'موقع السائق',
      'deliverd': 'تم التوصيل',
      'processing': 'قيد المعالجة',
      'canceled': 'ملغي',
      'no_orders_yet': 'لا توجد طلبات بعد',
      'no_orders_hint': 'ستظهر طلباتك هنا بعد إتمام الشراء',
      'detail': 'تفاصيل',
      'total_amount': 'المبلغ الإجمالي:  ',
      'order_no': 'رقم الطلب',
      'email_address': 'البريد الإلكتروني',
      'edit_your_personal_details': 'تعديل بياناتك الشخصية',
      'profile_updated_successfully': 'تم تحديث الملف الشخصي بنجاح',
      'name_required': 'الاسم مطلوب',
      'valid_email_required': 'بريد إلكتروني صحيح مطلوب',
      'email_already_in_use': 'هذا البريد مستخدم بالفعل من حساب آخر',
      'phone_already_in_use': 'هذا الرقم مستخدم بالفعل من حساب آخر',
      'success': 'تم بنجاح!',
      'order_will_be_delivered': 'سيتم توصيل طلبك قريباً.\n',
      'thank_you': 'شكراً لاختيارك تطبيقنا!',
      'track_your_orders': 'تتبع طلباتك',
      'back_to_home': 'العودة للرئيسية',
      'unknown_error': 'خطأ غير معروف، يرجى المحاولة لاحقاً',
      'share_feature_coming_soon': 'ميزة المشاركة قريباً',
      'order_subtotal': 'المجموع الفرعي للطلب:',
      'discount_percent': 'الخصم (%d%%):',
      'total_colon': 'الإجمالي:',
      'something_error': 'حدث خطأ',
      'error': 'خطأ',
      'registration_failed': 'فشل التسجيل',
      'create_account': 'إنشاء حساب',
      'create_account_subtitle': 'أنشئ حسابك للبدء.',
      'sign_up_as': 'سجل كـ:',
      'first_name': 'الاسم الأول',
      'last_name': 'الاسم الأخير',
      'first_name_required': 'الاسم الأول مطلوب',
      'last_name_required': 'الاسم الأخير مطلوب',
      'name_must_be_more_than_2': 'يجب أن يكون الاسم أكثر من حرفين',
      'enter_first_name': 'أدخل اسمك الأول',
      'enter_last_name': 'أدخل اسمك الأخير',
      'please_enter_email': 'يرجى إدخال بريد إلكتروني',
      'please_enter_valid_email': 'يرجى إدخال بريد إلكتروني صحيح',
      'enter_email': 'أدخل بريدك الإلكتروني',
      'phone_number_optional': 'رقم الهاتف (اختياري)',
      'enter_phone': 'أدخل رقم هاتفك',
      'address': 'العنوان',
      'address_required': 'العنوان مطلوب',
      'address_detailed': 'يجب أن يكون العنوان أكثر دقة وتفصيلاً',
      'enter_address': 'أدخل عنوانك',
      'postal_code': 'الرمز البريدي',
      'enter_postal_code': 'أدخل الرمز البريدي',
      'password_required': 'كلمة المرور مطلوبة',
      'password_min_length': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'password_complexity': 'يجب أن تحتوي كلمة المرور على حروف كبيرة وصغيرة وأرقام ورموز',
      'enter_password': 'أدخل كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'confirm_your_password': 'تأكيد كلمة المرور',
      'please_confirm_password': 'يرجى تأكيد كلمة المرور',
      'passwords_do_not_match': 'كلمات المرور غير متطابقة',
      'empty': 'فارغ',
      'not_match': 'غير متطابق',
      'enter_confirm_password': 'أدخل تأكيد كلمة المرور',
      'i_already_have_account': 'لدي حساب بالفعل!',
      'i_agree_terms': 'أوافق على شروط الخدمة وسياسة الخصوصية',
      'please_agree_terms': 'يرجى الموافقة على شروط الخدمة',
      'already_have_account': 'لديك حساب بالفعل؟ ',
      'register': 'تسجيل',
      'creating_account': 'جاري إنشاء الحساب...',
      'username': 'اسم المستخدم',
      'enter_username': 'أدخل اسم المستخدم',
      'username_required': 'اسم المستخدم مطلوب',
      'username_min_length': 'يجب أن يكون اسم المستخدم 3 أحرف على الأقل',
      'forgot_password': 'نسيت كلمة المرور؟',
      'forgot_password_title': 'نسيت كلمة المرور!',
      'forgot_password_subtitle': 'لا تقلق! يحدث. يرجى إدخال رقم الهاتف وسنرسل رمز التحقق.',
      'enter_phone_number': 'أدخل رقم الهاتف',
      'continue_btn': 'متابعة',
      'verification': 'التحقق',
      'otp_verification': 'التحقق بالرمز',
      'enter_otp': 'أدخل الرقم المرسل إلى ',
      'dont_receive_code': 'لم تستلم الرمز؟ ',
      'resend': 'إعادة إرسال',
      'submit': 'إرسال',
      'password_update_success': 'تم تحديث كلمة المرور\nبنجاح',
      'password_updated_message': 'تم تحديث كلمة المرور\nبنجاح',
      'sec': ' ثانية',
      'reset_password': 'إعادة تعيين كلمة المرور',
      'reset_password_subtitle': 'أدخل بريدك الإلكتروني وسنرسل رابط إعادة تعيين كلمة المرور.',
      'send_reset_link': 'إرسال رابط إعادة التعيين',
      'remember_password': 'تذكرت كلمة المرور؟ ',
      'login': 'تسجيل الدخول',
      'check_inbox': 'يرجى التحقق من بريدك الوارد والبريد المزعج.',
      'failed_send_reset': 'فشل إرسال رابط إعادة التعيين',
      'signing_in': 'جاري تسجيل الدخول...',
      'email_or_password_incorrect': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
      'welcome_back_title': 'مرحباً بعودتك!',
      'welcome_back_subtitle': 'مرحباً بعودتك، لقد اشتقنا لك',
      'first_time_here': 'هل هذه أول مرة؟ ',
      'signup': 'تسجيل ',
      'or_continue_with': 'أو المتابعة عبر',
      'google': 'Google',
      'apple': 'Apple',
      'welcome_to_shopease': 'مرحباً بك في ShopEase',
      'discover_best_products': 'اكتشف أفضل المنتجات مع توصيل سريع وموثوق.',
      'by_continuing_agree': 'بالمتابعة، أنت توافق على شروط الخدمة وسياسة الخصوصية',
      'shop': 'تسوق',
      'ease': 'سهل',
      'your_delivery_partner': 'شريك التوصيل الخاص بك',
      'welcome_back': 'مرحباً بعودتك',
      'sign_in_to_continue': 'سجل الدخول للمتابعة',
      'fill_details': 'املأ التفاصيل للبدء',
      'payment_successful': 'تم الدفع بنجاح',
      'payment_failed': 'فشل الدفع',
      'press_back_again_exit': 'اضغط مرة أخرى للخروج',
      'pick_location': 'اختر الموقع',
      'tap_map_to_set': 'اضغط على الخريطة لتحديد موقع التوصيل',
      'set_your_location': 'حدد موقعك',
      'save_and_continue': 'حفظ ومتابعة',
      'not_added_anything': 'لم تضف أي شيء بعد',
      'review_count': '(%d تقييم)',
      'login_title': 'تسجيل الدخول',
      'login_subtitle': 'أدخل بيانات الدخول للوصول إلى حسابك',
      'sign_up_user': 'تسجيل مستخدم ',
      'email_required': 'البريد الإلكتروني مطلوب',
      'valid_email': 'أدخل بريداً إلكترونياً صحيحاً',
      'dont_have_account': 'ليس لديك حساب؟ ',
      'password_required_field': 'كلمة المرور مطلوبة',
      'first_name_required_field': 'الاسم الأول مطلوب',
      'app_bar_search': 'بحث',
      'home_drawer': 'الرئيسية',
      'favourites_drawer': 'المفضلة',
      'profile_drawer': 'الملف الشخصي',
      'log_out_drawer': 'تسجيل الخروج',
      'online': 'متصل',
      'today': 'اليوم',
      'connecting_deliveries': 'جاري توصيل الطلبات...',
      'fast_shipping_low_costs': 'شحن سريع بتكاليف\nمنخفضة',
      'exit': 'خروج',
      'driver_management': 'إدارة السائقين',
      'driver_management_soon': 'إدارة السائقين قريباً',
      'edit_user_info': 'تعديل بيانات المستخدم',
      'button_text': 'زر',
      'accepted_orders': 'الطلبات المقبولة',
      'your_state': 'حالتك',
      'order_details': 'تفاصيل الطلب',
      'items': 'المنتجات',
      'product': 'المنتج',
      'order_date': 'تاريخ الطلب',
      'order_status': 'حالة الطلب',
      'cancel_order': 'إلغاء الطلب',
      'cancel_order_confirm': 'هل أنت متأكد من إلغاء هذا الطلب؟',
      'order_cancelled': 'تم إلغاء الطلب بنجاح',
      'yes': 'نعم',
      'no': 'لا',
      'reviews': 'التقييمات',
      'write_review': 'كتابة تقييم',
      'review_hint': 'شارك رأيك في هذا المنتج...',
      'no_reviews_yet': 'لا توجد تقييمات بعد',
      'rate_driver': 'تقييم السائق',
      'driver_rated': 'تم تقييم السائق',
      'chat_with_driver': 'محادثة مع السائق',
      'min_price': 'السعر الأدنى',
      'max_price': 'السعر الأقصى',
      'order_again': 'إعادة الطلب',
      'items_added_to_cart': 'تمت إضافة العناصر إلى السلة',
    },
  };

  String tr(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get t =>
      Localizations.of<AppLocalizations>(this, AppLocalizations)!;
}
