import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_name': 'ShipLink',
      'ship_link': 'Ship Link',
      'home': 'Home',
      'search': 'Search',
      'search_orders': 'Search by order ID or customer ID',
      'search_users': 'Search users by name, email or phone',
      'search_drivers': 'Search drivers by name, email or phone',
      'cart': 'Cart',
      'profile': 'Profile',
      'my_profile': 'My Profile',
      'orders': 'Orders',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'sign_out': 'Sign Out',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'full_name': 'Full Name',
      'phone_number': 'Phone Number',
      'shipments': 'Shipments',
      'track_shipment': 'Track Shipment',
      'delivery_address': 'Delivery Address',
      'delivery_instructions': 'Delivery Instructions',
      'show_order_qr': 'Show Order QR',
      'show_qr_to_driver': 'Show this QR code to the driver to scan before delivery.',
      'delivery_instructions_hint': 'e.g. Leave at the door, call me when you arrive',
      'payment': 'Payment',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'top_sellers': 'Best Seller',
      'all_products': 'All Products',
      'add_to_cart': 'Add to Cart',
      'checkout': 'Checkout',
      'total': 'Total',
      'today': 'Today',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'orders_trend': 'Orders Trend (Last 7 Days)',
      'subtotal': 'Subtotal',
      'discount': 'Discount',
      'original_price': 'Original Price',
      'driver_mode': 'Driver Mode',
      'accept_order': 'Accept Order',
      'live_tracking': 'Live Tracking',
      'settings': 'Settings',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'orders_history': 'Orders History',
      'my_orders': 'My Orders',
      'pending': 'Pending',
      'shipped': 'Shipped',
      'in_transit': 'In Transit',
      'delivered': 'Delivered',
      'cancelled': 'Cancelled',
      'account_settings': 'Account Settings',
      'personal_information': 'Personal Information',
      'address_book': 'Address Book',
      'payment_methods': 'Payment Methods',
      'notifications': 'Notifications',
      'notification_preferences': 'Notification Preferences',
      'order_updates': 'Order Updates',
      'chat_messages': 'Chat Messages',
      'promotions': 'Promotions',
      'you_may_also_like': 'You May Also Like',
      'choose_from_gallery': 'Choose from gallery',
      'take_a_photo': 'Take a photo',
      'referral_code': 'Referral Code',
      'share_code_description':
          'Share your code with friends and earn rewards!',
      'download_invoice': 'Download Invoice',
      'mute_notifications': 'Mute Notifications',
      'unmute_notifications': 'Unmute Notifications',
      'notifications_muted_for_order': 'Notifications muted for this order',
      'notifications_unmuted_for_order': 'Notifications unmuted for this order',
      'earnings_overview': 'Earnings Overview',
      'order_status_distribution': 'Order Status Distribution',
      'my_chats': 'My Chats',
      'security': 'Security',
      'support': 'Support',
      'help_center': 'Help Center',
      'contact_us': 'Contact Us',
      'about_shiplink': 'About ShipLink',
      'log_out': 'Log Out',
      'save_changes': 'Save Changes',
      'edit_profile': 'Edit Profile',
      'add_address': 'Add Address',
      'edit_address': 'Edit Address',
      'save_address': 'Save Address',
      'update_address': 'Update Address',
      'pick_from_maps': 'Pick from Google Maps',
      'confirm_location': 'Confirm Location',
      'default_address': 'Default',
      'set_as_default': 'Set as Default',
      'set_default_success': 'Default address updated',
      'tap_to_set_default': 'Tap to set as default',
      'delete': 'Delete',
      'edit': 'Edit',
      'no_addresses': 'No addresses saved yet',
      'tap_add_address': 'Tap + to add a new address',
      'label': 'Label',
      'city': 'City',
      'street': 'Street',
      'building': 'Building',
      'apartment': 'Apartment',
      'full_address': 'Full Address',
      'enter_address_manually': 'Enter address manually or use Google Maps',
      'apt': 'Apt',
      'no_favourites': 'No favourites yet',
      'tap_heart_to_save': 'Tap the heart on any product to save it here',
      'your_cart_is_empty': 'Your cart is empty',
      'not_added_anything_yet': 'Not added anything yet',
      'start_shopping': 'Start Shopping',
      'promo_code': 'Promo Code',
      'apply': 'Apply',
      'percent_off_applied': '% off applied!',
      'invalid_promo_code': 'Invalid promo code',
      'search_products': 'Search products...',
      'no_results': 'No results found',
      'no_users': 'No users found',
      'user_deleted': 'User deleted successfully',
      'no_drivers': 'No drivers found',
      'no_orders': 'No orders found',
      'load_more': 'Load more',
      'date': 'Date',
      'products': 'Products',
      'active_products': 'Active Products',
      'low_stock': 'Low Stock',
      'products_by_category': 'Products by Category',
      'add_product': 'Add Product',
      'edit_product': 'Edit Product',
      'description': 'Description',
      'price': 'Price',
      'qty': 'Quantity',
      'image_url': 'Image URL',
      'upload_image': 'Upload Image',
      'on_offer': 'On Offer',
      'offer_price': 'Offer Price',
      'top_seller': 'Top Seller',
      'inactive': 'Inactive',
      'no_products': 'No products found',
      'product_saved': 'Product saved successfully',
      'product_deleted': 'Product deleted successfully',
      'products_deleted': 'Products deleted successfully',
      'delete_product': 'Delete Product',
      'delete_product_confirm': 'Are you sure you want to delete',
      'select': 'Select',
      'cancel': 'Cancel',
      'delete_selected': 'Delete Selected',
      'delete_selected_confirm': 'Are you sure you want to delete the selected items',
      'search_for_products': 'Search for products',
      'categories': 'Categories',
      'filtered_products': 'Filtered Products',
      'clear_filter': 'Clear',
      'sort_default': 'Default',
      'sort_price_asc': 'Price ↑',
      'sort_price_desc': 'Price ↓',
      'sort_newest': 'Newest',
      'sort_name_az': 'A-Z',
      'sort_name_za': 'Z-A',
      'view_all': 'View All',
      'all': 'All',
      'quantity': 'Quantity',
      'added_to_cart': 'Added to cart',
      'removed_from_cart': 'Removed from cart',
      'item_removed_from_cart': 'removed from cart',
      'proceed_to_checkout': 'Proceed to Checkout',
      'order_history': 'Order History',
      'order_code': 'Your Order Code:',
      'reward_points': 'Reward Points',
      'two_factor_auth': 'Two-Factor Authentication',
      'change_password': 'Change Password',
      'set_new_password': 'Set New Password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'password_updated': 'Password updated successfully',
      'active_sessions': 'Active Sessions',
      'security_tips': 'Tips to keep your account secure',
      'security_settings': 'Security Settings',
      'tip_strong_password': 'Use a strong, unique password',
      'tip_enable_2fa': 'Enable two-factor authentication',
      'tip_review_sessions': 'Review active sessions regularly',
      'english': 'English',
      'arabic': 'العربية',
      'browse': 'BROWSE',
      'logout': 'Logout',
      'logout_confirm_title': 'Log Out',
      'are_you_sure_logout': 'Are you sure you want to log out?',
      'logout_successful': 'Logout Successful',
      'top_categories': 'Top Categories',
      'top_seller_products': 'Top Seller Products',
      'category_mobile_accessories': 'Mobile Accessories',
      'category_watches': 'Watches',
      'category_mens_shirts': "Men's Shirts",
      'category_mens_shoes': "Men's Shoes",
      'category_mens_watches': "Men's Watches",
      'category_laptops': 'Laptops',
      'category_kitchen_accessories': 'Kitchen Accessories',
      'category_home_decoration': 'Home Decoration',
      'category_furniture': 'Furniture',
      'category_beauty': 'Beauty',
      'category_fragrances': 'Fragrances',
      'category_groceries': 'Groceries',
      'category_smartphones': 'Smartphones',
      'category_clothing': 'Clothing',
      'category_automotive': 'Automotive',
      'category_skincare': 'Skincare',
      'category_sports': 'Sports',
      'category_toys': 'Toys',
      'category_books': 'Books',
      'my_favourites': 'My Favourites',
      'out_of_stock': 'Out of Stock',
      'notify_when_available': 'Notify when available',
      'product_not_found': 'Product not found',
      'my_cart': 'My Cart',
      'no_products_found': 'No products found',
      'could_not_load_products': 'Could not load products',
      'retry': 'Retry',
      'category': 'Category',
      'all_categories': 'All Categories',
      'date': 'Date',
      'name': 'Name',
      'back': 'Back',
      'old_price': 'Old Price',
      'yes': 'Yes',
      'no': 'No',
      'description': 'Description',
      'popular': 'Popular',
      'top_seller': 'Top Seller',
      'explore': 'Explore',
      'developed_by': 'Developed by MahmoudFahmy \u00a9 2023',
      'guest': 'Guest',
      'special_offer': 'Special Offer',
      'up_to_off': 'Up to % OFF',
      'shop_now': 'Shop Now',
      'lets_go': "Let's Go",
      'get_special_discount': 'Get Special Discount\n',
      'offer_up_to': 'Up to  ',
      'no_notifications_yet': 'No notifications yet',
      'mark_read': 'Mark read',
      'driver_location': 'Driver Location',
      'deliverd': 'Delivered',
      'processing': 'Processing',
      'canceled': 'Canceled',
      'no_orders_yet': 'No orders yet',
      'no_orders_hint': 'Your orders will appear here after checkout',
      'detail': 'Detail',
      'total_amount': 'Total Amount:  ',
      'order_no': 'Order No',
      'email_address': 'Email Address',
      'edit_your_personal_details': 'Edit your personal details',
      'profile_updated_successfully': 'Profile updated successfully',
      'name_required': 'Name is required',
      'valid_email_required': 'Valid email is required',
      'email_already_in_use': 'This email is already in use by another account',
      'phone_already_in_use':
          'This phone number is already in use by another account',
      'verification_email_sent': 'Verification email sent to {email}. Please check your inbox to confirm.',
      'success': 'SUCCESS!',
      'order_will_be_delivered': 'Your order will be delivered soon.\n',
      'thank_you': 'Thank you for choosing our app!',
      'track_your_orders': 'Track your orders',
      'back_to_home': 'Back To Home',
      'unknown_error': 'Unknown Error,Please try again later ',
      'share_feature_coming_soon': 'Share feature coming soon',
      'order_subtotal': 'Order Subtotal:',
      'discount_percent': 'Discount (%d%%):',
      'total_colon': 'Total:',
      'something_error': 'something error',
      'error': 'Error',
      'registration_failed': 'Registration failed',
      'create_account': 'Create Account',
      'create_account_subtitle': 'Create your account to get started.',
      'sign_up_as': 'SignUp as:',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'first_name_required': 'first name is required',
      'last_name_required': 'last name is required',
      'name_must_be_more_than_2': 'Name must be more than 2 characters',
      'enter_first_name': 'Enter Your First Name',
      'enter_last_name': 'Enter Your Last Name',
      'please_enter_email': 'Please enter an email address',
      'please_enter_valid_email': 'Please enter a valid email address',
      'enter_email': 'Enter Your Email',
      'enter_full_name': 'Enter your full name',
      'phone_number_optional': 'Phone Number (Optional)',
      'enter_phone': 'Enter Your Phone Number',
      'address': 'Address',
      'address_required': 'address is required',
      'address_detailed': 'address must be more accurate and detailed',
      'enter_address': 'Enter Your Address',
      'postal_code': 'Postal Code',
      'enter_postal_code': 'Enter Your Postal Code',
      'password_required': 'Password is required',
      'password_requirements': 'Must be at least 6 characters',
      'password_min_length': 'Password must be at least 6 characters',
      'update_password': 'Update Password',
      'password_complexity':
          'Password should contain upper, lower, digit and Special character',
      'password_strength': 'Password strength',
      'password_weak': 'Weak',
      'password_medium': 'Medium',
      'password_strong': 'Strong',
      'show_password': 'Show password',
      'hide_password': 'Hide password',
      'remember_me': 'Remember me',
      'postal_required': 'Postal code is required',
      'postal_invalid': 'Enter a valid postal code',
      'enter_password': 'Enter Your Password',
      'confirm_password': 'Confirm Password',
      'confirm_your_password': 'Confirm your password',
      'please_confirm_password': 'Please confirm your password',
      'passwords_do_not_match': 'Passwords do not match',
      'empty': 'Empty',
      'not_match': 'Not Match',
      'enter_confirm_password': 'Enter Your Confirm Password',
      'i_already_have_account': 'I already have an account!',
      'i_agree_terms': 'I agree to the Terms of Service and Privacy Policy',
      'please_agree_terms': 'Please agree to the Terms of Service',
      'already_have_account': 'Already have an account? ',
      'register': 'Register',
      'creating_account': 'Creating Account...',
      'username': 'Username',
      'enter_username': 'Enter your username',
      'username_required': 'Username is required',
      'username_min_length': 'Username must be at least 3 characters',
      'forgot_password': 'Forgot Password?',
      'forgot_password_title': 'Forgot Password!',
      'forgot_password_subtitle':
          "Don't worry! It happens. Please enter the phone number we will send the OTP to.",
      'enter_phone_number': 'Enter the phone number',
      'continue_btn': 'Continue',
      'verification': 'Verification',
      'otp_verification': 'OTP VERIFICATION',
      'enter_otp': 'Enter the OTP sent to ',
      'dont_receive_code': "Don't receive code? ",
      'resend': 'Re-send',
      'submit': 'Submit',
      'password_update_success': 'Password Update \nSuccessfully',
      'password_updated_message':
          'your password has been \nupdated successfully',
      'sec': ' Sec',
      'reset_password': 'Reset Password',
      'reset_password_subtitle':
          "Enter your email address and we'll send you a link to reset your password.",
      'send_reset_link': 'Send Reset Link',
      'remember_password': 'Remember your password? ',
      'login': 'Login',
      'check_inbox': 'Please check your inbox and spam folder.',
      'failed_send_reset': 'Failed to send reset link',
      'signing_in': 'Signing In...',
      'email_or_password_incorrect': 'Email or Password Incorrect',
      'welcome_back_title': 'Welcome Back!',
      'welcome_back_subtitle': 'welcome back we missed you',
      'first_time_here': 'First time here? ',
      'signup': 'SignUp ',
      'or_continue_with': 'Or continue with',
      'google': 'Google',
      'apple': 'Apple',
      'welcome_to_shopease': 'Welcome to ShopEase',
      'discover_best_products':
          'Discover the best products with fast and reliable delivery.',
      'by_continuing_agree':
          'By continuing, you agree to our Terms of Service and Privacy Policy',
      'shop': 'Shop',
      'ease': 'Ease',
      'your_delivery_partner': 'Your delivery partner',
      'welcome_back': 'Welcome Back',
      'sign_in_to_continue': 'Sign in to continue',
      'fill_details': 'Fill in the details to get started',
      'payment_successful': 'Payment Successful',
      'payment_failed': 'Payment Failed',
      'press_back_again_exit': 'Press back again to exit',
      'pick_location': 'Pick Location',
      'tap_map_to_set': 'Tap on the map to set your delivery location',
      'set_your_location': 'Set Your Location',
      'save_and_continue': 'Save & Continue',
      'not_added_anything': 'Not added anything yet',
      'review_count': '(%d reviews)',
      'login_title': 'LOGIN',
      'login_subtitle': 'Enter your credentials to access your account',
      'sign_up_user': 'Sign UP User ',
      'email_required': 'Email is required',
      'valid_email': 'Enter a valid email address',
      'dont_have_account': "Don't have an account? ",
      'password_required_field': 'Password is required',
      'first_name_required_field': 'first name is required',
      'app_bar_search': 'Search',
      'home_drawer': 'Home',
      'favourites_drawer': 'Favourites',
      'profile_drawer': 'Profile',
      'log_out_drawer': 'Logout',
      'online': 'Online',
      'today': 'Today',
      'connecting_deliveries': 'Connecting Deliveries...',
      'fast_shipping_low_costs': 'Fast Shipping at Low\nCosts',
      'exit': 'Exit',
      'driver_management': 'Driver Management',
      'driver_management_soon': 'Driver management coming soon',
      'edit_user_info': 'Edit User Info',
      'button_text': 'Button',
      'accepted_orders': 'Accepted Orders',
      'your_state': 'Your State',
      'order_details': 'Order Details',
      'items': 'Items',
      'product': 'Product',
      'order_date': 'Order Date',
      'order_status': 'Order Status',
      'cancel_order': 'Cancel Order',
      'cancel_order_confirm': 'Are you sure you want to cancel this order?',
      'order_cancelled': 'Order cancelled successfully',
      'yes': 'Yes',
      'no': 'No',
      'reviews': 'Reviews',
      'write_review': 'Write a Review',
      'review_hint': 'Share your thoughts about this product...',
      'no_reviews_yet': 'No reviews yet',
      'rate_driver': 'Rate Driver',
      'driver_rated': 'Driver rated',
      'chat_with_driver': 'Chat with Driver',
      'min_price': 'Min price',
      'max_price': 'Max price',
      'order_again': 'Order Again',
      'items_added_to_cart': 'Items added to cart',
      'paid': 'Paid',
      'cod': 'COD',
      'ship_link_driver': 'ShipLink - Driver',
      'ship_link_driver_splash': 'ShipLink Driver',
      'driver': 'Driver',
      'welcome_back_captain': 'Welcome back, Captain!',
      'sign_in_to_start': 'Sign in to start delivering',
      'email_is_required': 'Email is required',
      'password_is_required': 'Password is required',
      'forgot_password_q': 'Forgot Password?',
      'dont_have_account_q': "Don't have an account? ",
      'login_driver': 'LOGIN Driver',
      'enter_your_credentials':
          'Enter your credentials to access your\n account',
      'first_time_here_q': 'First time here? ',
      'signup_': 'SignUp ',
      'create_driver_account': 'Create Driver Account',
      'fill_details_to_start': 'Fill in your details to get started',
      'name_is_required': 'Name is required',
      'name_min_2_chars': 'Name must be more than 2 characters',
      'email_is_required_2': 'Email is required',
      'invalid_email': 'Invalid email',
      'email_address_2': 'Email address',
      'phone_11_digits': 'Phone must be 11 digits',
      'vehicle_information': 'Vehicle Information',
      'vehicle_type': 'Vehicle type',
      'select_vehicle_type': 'Select vehicle type',
      'required_field': 'Required',
      'bike_type_hint': 'Bike type (e.g. Mountain, Electric)',
      'vehicle_number': 'Vehicle number',
      'governorate': 'Governorate',
      'select_governorate': 'Select governorate',
      'security_section': 'Security',
      'password_required_2': 'Password required',
      'min_6_characters': 'Min 6 characters',
      'already_have_account_q': 'Already have an account? ',
      'sign_in_short': 'Sign In',
      'driver_registered_success': 'Driver registered successfully',
      'something_went_wrong': 'Something went wrong. Please try again later.',
      'hello': 'Hello',
      'ready_for_deliveries': 'Ready for deliveries',
      'youre_offline': "You're offline",
      'offline': 'Offline',
      'active': 'Active',
      'rating': 'Rating',
      'accepted': 'Accepted',
      'picked_up': 'Picked Up',
      'active_delivery': 'Active Delivery',
      'customer': 'Customer',
      'user_details': 'User Details',
      'egp': 'EGP',
      'mark_picked_up': 'Mark Picked Up',
      'mark_shipped': 'Mark Shipped',
      'mark_delivered': 'Mark Delivered',
      'available_orders': 'Available Orders',
      'map': 'Map',
      'no_orders_available': 'No orders available',
      'check_back_later': 'Check back later for new orders',
      'switch_to_orders_tab': 'Switch to Orders tab to accept',
      'order': 'Order',
      'phone_number_label': 'Phone Number : +2',
      'some_error_try_again': 'someThing error please try again later',
      'untrusted_url': 'Untrusted URL',
      'no_chats_yet': 'No chats yet',
      'chat_with_users': 'Chat with users after accepting orders',
      'no_messages_yet': 'No messages yet',
      'now': 'now',
      'minutes_ago': 'm',
      'hours_ago': 'h',
      'days_ago': 'd',
      'date_format': '{day}/{month}',
      'selected_count': 'selected',
      'messages_deleted': 'Messages deleted',
      'delete_failed': 'Delete failed',
      'orders_map': 'Orders Map',
      'you': 'You',
      'order_accepted': 'Order accepted',
      'order_has_been_accepted': 'Order has been accepted',
      'view_route': 'View Route',
      'show_route': 'Show Route',
      'personal_info': 'Personal Info',
      'name_phone_email': 'Name, phone, email',
      'vehicle_info': 'Vehicle Info',
      'vehicle_type_number': 'Vehicle type, number',
      'bank_account_earnings': 'Bank account, earnings',
      'app_preferences': 'App preferences',
      'help_support': 'Help & Support',
      'contact_us_faq': 'Contact us, FAQ',
      'something_went_wrong_short': 'Something went wrong',
      'initials_placeholder': 'JD',
      'trips': 'Trips',
      'week': 'Week',
      'close': 'Close',
      'type': 'Type',
      'number': 'Number',
      'vehicle_info_title': 'Vehicle Info',
      'payment_title': 'Payment',
      'today_earnings': 'Today',
      'this_week': 'This Week',
      'all_time': 'All Time',
      'status': 'Status',
      'status_updated': 'Status updated',
      'logged_out_successfully': 'Logged out successfully',
      'edit_info': 'Edit Info',
      'enter_your_name': 'Enter your name',
      'save': 'Save',
      'logout_successfully': 'Logout Successfuly',
      'logout_btn': 'LogOut',
      'driver_profile': 'Driver Profile',
      'enter_your_name_hint': 'enter your name',
      'enter_phone_hint': 'enter your PhoneNumber',
      'update_info_successfully': 'Update Info Successfully',
      'user': 'User',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      'orders_tab': 'Orders',
      'available': 'Available',
      'accepted_tab': 'Accepted',
      'completed': 'Completed',
      'no_available_orders': 'No available orders',
      'try_again_later': 'Try Again Later',
      'no_accepted_orders': 'No accepted orders',
      'no_completed_orders': 'No completed orders yet',
      'offline_cached_orders': 'Offline — showing cached orders',
      'km': 'km',
      'away': 'away',
      'delivery': 'Delivery',
      'distance': 'Distance',
      'est_time': 'Est. time',
      'chat': 'Chat',
      'navigate': 'Navigate',
      'straight_line_estimate':
          'Straight-line estimate — open Google Maps for precise routing',
      'min': 'min',
      'home_bottom': 'Home',
      'orders_bottom': 'Orders',
      'profile_bottom': 'Profile',
      'bike': 'Bike',
      'motorcycle': 'Motorcycle',
      'car': 'Car',
      'alexandria': 'Alexandria',
      'aswan': 'Aswan',
      'asyut': 'Asyut',
      'beheira': 'Beheira',
      'beni_suef': 'Beni Suef',
      'cairo': 'Cairo',
      'dakahlia': 'Dakahlia',
      'damietta': 'Damietta',
      'faiyum': 'Faiyum',
      'gharbia': 'Gharbia',
      'giza': 'Giza',
      'ismailia': 'Ismailia',
      'kafr_el_sheikh': 'Kafr El Sheikh',
      'luxor': 'Luxor',
      'matruh': 'Matruh',
      'minya': 'Minya',
      'monufia': 'Monufia',
      'new_valley': 'New Valley',
      'north_sinai': 'North Sinai',
      'port_said': 'Port Said',
      'qalyubia': 'Qalyubia',
      'qena': 'Qena',
      'red_sea': 'Red Sea',
      'sharqia': 'Sharqia',
      'sohag': 'Sohag',
      'south_sinai': 'South Sinai',
      'suez': 'Suez',
      'password_label': 'Password',
      'captain': 'Captain',
      'no_orders_available_driver': 'No orders available',
      'call': 'Call',
      'send_message': 'Send Message',
      'start_delivery': 'Start Delivery',
      'complete_delivery': 'Complete Delivery',
      'payment_method': 'Payment Method',
      'cash_on_delivery': 'Cash on Delivery',
      'scan_to_deliver': 'Scan to Deliver',
      'online_payment': 'Online Payment',
      'customer_details': 'Customer Details',
      'notes': 'Notes',
      'no_notes': 'No Notes',
      'reject_order': 'Reject Order',
      'confirm_cancel': 'Are you sure you want to cancel?',
      'total_earnings': 'Total Earnings',
      'completed_trips': 'Completed Trips',
      'cancelled_trips': 'Cancelled Trips',
      'earnings': 'Earnings',
      'week_earnings': 'This Week',
      'all_time_earnings': 'All Time',
      'no_notifications': 'No Notifications',
      'clear_all': 'Clear All',
      'connection_lost': 'Connection Lost',
      'check_internet': 'Check your internet connection',
      'try_again': 'Try Again',
      'loading': 'Loading...',
      'error_loading': 'Error loading data',
      'no_history': 'No History',
      'filter': 'Filter',
      'today_short': 'Today',
      'yesterday': 'Yesterday',
      'this_week_short': 'This Week',
      'this_month': 'This Month',
      'search_orders': 'Search orders...',
      'no_results': 'No Results',
      'driving_directions': 'Directions',
      'you_have_arrived': 'You have arrived',
      'customer_phone': 'Customer Phone',
      'pickup_location': 'Pickup Location',
      'dropoff_location': 'Dropoff Location',
      'delivery_fee': 'Delivery Fee',
      'no_reviews': 'No Reviews',
      'confirm_logout': 'Are you sure you want to log out?',
      'update_profile': 'Update Profile',
      'phone_required': 'Phone number is required',
      'phone_invalid': 'Phone number must be at least 10 digits',
      'order_placed': 'Order Placed',
      'confirmed': 'Confirmed',
      'out_for_delivery': 'Out for Delivery',
      'order_progress': 'Order Progress',
      'current_status': 'Current',
      'reorder': 'Reorder',
      'save_for_later': 'Save for Later',
      'saved_for_later': 'Saved for later',
      'move_to_cart': 'Move to Cart',
      'saved_items': 'Saved Items',
      'open_in_maps': 'Open in Maps',
      'error_unknown': 'Something went wrong. Please try again.',
      'error_network': 'Network error. Please check your connection and try again.',
      'error_timeout': 'Connection timed out. Please try again.',
      'error_invalid_credentials': 'Invalid email or password. Please check your credentials and try again.',
      'error_email_already_registered': 'This email is already registered. Please login or use a different email.',
      'error_email_not_confirmed': 'Please confirm your email address before logging in. Check your inbox.',
      'error_invalid_email': 'Please enter a valid email address.',
      'error_phone_already_registered': 'This phone number is already registered. Please use a different number.',
      'error_user_not_found': 'No account found with this email. Please create an account.',
      'error_rate_limit': 'Too many attempts. Please wait a moment and try again.',
      'error_link_expired': 'This link has expired. Please request a new one.',
      'error_weak_password': 'Password is too weak. Use at least 8 characters with uppercase, lowercase and numbers.',
      'error_same_password': 'New password must be different from the current one.',
      'error_duplicate_entry': 'This information already exists. Please use different details.',
      'error_not_found': 'The requested information was not found.',
      'error_permission_denied': 'You do not have permission to perform this action.',
      'error_required_field': 'Please fill in all required fields.',
      'error_invalid_value': 'Please enter a valid value.',
      'error_file_not_found': 'File not found.',
      'error_file_too_large': 'File is too large. Please choose a smaller file.',
      'error_invalid_data': 'Invalid data received. Please try again.',
      'payment_opened_new_tab': 'Payment page opened in a new tab. Complete payment there.',
      'failed_download_invoice': 'Failed to download invoice',
      'no_payment_methods': 'No payment methods',
      'add_card_hint': 'Add a card for faster checkout',
      'add_card': 'Add Card',
      'complete_card_setup': 'Complete card setup in the new tab',
      'failed_card_setup': 'Failed to start card setup',
      'set_default': 'Set as Default',
      'coming_soon': 'Coming soon',
      'payment_network_error': 'Payment service unreachable. Check your connection.',
      'admin_login_subtitle': 'Sign in with your admin credentials to manage the platform.',
      'dashboard_overview': 'Overview',
      'dashboard': 'Dashboard',
      'users': 'Users',
      'drivers': 'Drivers',
      'orders': 'Orders',
      'revenue': 'Revenue',
      'activate': 'Activate',
      'driver_activated': 'Driver activated',
      'driver_details': 'Driver Details',
      'activate_driver_title': 'Activate Driver',
      'activate_driver_confirm': 'Are you sure you want to activate this driver?',
      'sign_out_title': 'Sign Out',
      'sign_out_confirm': 'Are you sure you want to sign out?',
      'incomplete': 'Incomplete',
      'customer': 'Customer',
      'details': 'Details',
      'order_status': 'Order Status',
      'order_details': 'Order Details',
      'cancel_order_title': 'Cancel Order',
      'cancel_order_confirm': 'Are you sure you want to cancel this order? This cannot be undone.',
      'status_updated': 'Order status updated',
    },
    'ar': {
      'app_name': 'ShipLink',
      'ship_link': 'Ship Link',
      'home': 'الرئيسية',
      'search': 'بحث',
      'search_orders': 'بحث برقم الأوردر أو معرف العميل',
      'search_users': 'بحث بالاسم أو الإيميل أو التليفون',
      'search_drivers': 'بحث بالاسم أو الإيميل أو التليفون',
      'cart': 'السلة',
      'profile': 'الملف الشخصي',
      'my_profile': 'ملفي الشخصي',
      'orders': 'الطلبات',
      'sign_in': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'sign_out': 'تسجيل الخروج',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'name': 'الاسم',
      'full_name': 'الاسم الكامل',
      'phone_number': 'رقم الهاتف',
      'shipments': 'الشحنات',
      'track_shipment': 'تتبع الشحنة',
      'delivery_address': 'عنوان التوصيل',
      'delivery_instructions': 'تعليمات التوصيل',
      'show_order_qr': 'إظهار رمز QR',
      'show_qr_to_driver': 'أظهر رمز QR هذا للسائق لمسحه قبل التوصيل.',
      'delivery_instructions_hint': 'مثال: اتركها عند الباب، كلمني لما توصل',
      'payment': 'الدفع',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'top_sellers': 'الأكثر مبيعاً',
      'today': 'اليوم',
      'this_week': 'هذا الأسبوع',
      'this_month': 'هذا الشهر',
      'orders_trend': 'اتجاه الطلبات (آخر 7 أيام)',
      'all_products': 'جميع المنتجات',
      'add_to_cart': 'أضف إلى السلة',
      'checkout': 'إتمام الشراء',
      'total': 'الإجمالي',
      'subtotal': 'المجموع الفرعي',
      'discount': 'الخصم',
      'original_price': 'السعر الأصلي',
      'driver_mode': 'وضع السائق',
      'accept_order': 'قبول الطلب',
      'live_tracking': 'تتبع مباشر',
      'settings': 'الإعدادات',
      'dark_mode': 'الوضع الليلي',
      'language': 'اللغة',
      'orders_history': 'سجل الطلبات',
      'my_orders': 'طلباتي',
      'pending': 'قيد الانتظار',
      'shipped': 'تم الشحن',
      'in_transit': 'قيد التوصيل',
      'delivered': 'تم التوصيل',
      'cancelled': 'ملغي',
      'account_settings': 'إعدادات الحساب',
      'personal_information': 'المعلومات الشخصية',
      'address_book': 'دفتر العناوين',
      'payment_methods': 'طرق الدفع',
      'notifications': 'الإشعارات',
      'notification_preferences': 'إعدادات الإشعارات',
      'order_updates': 'تحديثات الطلبات',
      'chat_messages': 'رسائل المحادثة',
      'promotions': 'العروض',
      'you_may_also_like': 'قد يعجبك أيضاً',
      'choose_from_gallery': 'اختر من المعرض',
      'take_a_photo': 'التقاط صورة',
      'referral_code': 'كود الإحالة',
      'share_code_description': 'شارك الكود مع أصدقائك واكسب المكافآت!',
      'download_invoice': 'تنزيل الفاتورة',
      'mute_notifications': 'كتم الإشعارات',
      'unmute_notifications': 'إلغاء كتم الإشعارات',
      'notifications_muted_for_order': 'تم كتم الإشعارات لهذا الطلب',
      'notifications_unmuted_for_order': 'تم إلغاء كتم الإشعارات لهذا الطلب',
      'earnings_overview': 'نظرة عامة على الأرباح',
      'order_status_distribution': 'توزيع حالات الطلبات',
      'my_chats': 'محادثاتي',
      'security': 'الأمان',
      'support': 'الدعم',
      'help_center': 'مركز المساعدة',
      'contact_us': 'اتصل بنا',
      'about_shiplink': 'عن ShipLink',
      'log_out': 'تسجيل الخروج',
      'save_changes': 'حفظ التغييرات',
      'edit_profile': 'تعديل الملف الشخصي',
      'add_address': 'إضافة عنوان',
      'edit_address': 'تعديل العنوان',
      'save_address': 'حفظ العنوان',
      'update_address': 'تحديث العنوان',
      'pick_from_maps': 'اختيار من خرائط جوجل',
      'confirm_location': 'تأكيد الموقع',
      'default_address': 'افتراضي',
      'set_as_default': 'تعيين كافتراضي',
      'set_default_success': 'تم تحديث العنوان الافتراضي',
      'tap_to_set_default': 'اضغط لتعيين كافتراضي',
      'delete': 'حذف',
      'edit': 'تعديل',
      'no_addresses': 'لا توجد عناوين محفوظة',
      'tap_add_address': 'اضغط + لإضافة عنوان جديد',
      'label': 'تسمية',
      'city': 'المدينة',
      'street': 'الشارع',
      'building': 'المبنى',
      'apartment': 'الشقة',
      'full_address': 'العنوان الكامل',
      'enter_address_manually': 'أدخل العنوان يدوياً أو استخدم خرائط جوجل',
      'apt': 'شقة',
      'no_favourites': 'لا توجد مفضلات',
      'tap_heart_to_save': 'اضغط على القلب على أي منتج لحفظه هنا',
      'your_cart_is_empty': 'سلتك فارغة',
      'not_added_anything_yet': 'لم تضف أي شيء بعد',
      'start_shopping': 'ابدأ التسوق',
      'promo_code': 'كود الخصم',
      'apply': 'تطبيق',
      'percent_off_applied': '% خصم مطبق!',
      'invalid_promo_code': 'كود خصم غير صالح',
      'search_products': 'ابحث عن منتجات...',
      'no_results': 'لا توجد نتائج',
      'no_users': 'لا يوجد مستخدمين',
      'user_deleted': 'تم حذف المستخدم بنجاح',
      'no_drivers': 'لا يوجد سائقين',
      'no_orders': 'لا يوجد طلبات',
      'load_more': 'تحميل المزيد',
      'date': 'التاريخ',
      'products': 'المنتجات',
      'active_products': 'المنتجات النشطة',
      'low_stock': 'مخزون منخفض',
      'products_by_category': 'المنتجات حسب الفئة',
      'add_product': 'إضافة منتج',
      'edit_product': 'تعديل منتج',
      'description': 'الوصف',
      'price': 'السعر',
      'qty': 'الكمية',
      'image_url': 'رابط الصورة',
      'upload_image': 'رفع صورة',
      'on_offer': 'عرض خاص',
      'offer_price': 'سعر العرض',
      'top_seller': 'الأكثر مبيعاً',
      'inactive': 'غير مفعل',
      'no_products': 'لا يوجد منتجات',
      'product_saved': 'تم حفظ المنتج بنجاح',
      'product_deleted': 'تم حذف المنتج بنجاح',
      'products_deleted': 'تم حذف المنتجات بنجاح',
      'delete_product': 'حذف منتج',
      'delete_product_confirm': 'هل أنت متأكد من حذف',
      'select': 'تحديد',
      'cancel': 'إلغاء',
      'delete_selected': 'حذف المحدد',
      'delete_selected_confirm': 'هل أنت متأكد من حذف العناصر المحددة',
      'search_for_products': 'ابحث عن منتجات',
      'categories': 'التصنيفات',
      'filtered_products': 'المنتجات المفلترة',
      'clear_filter': 'مسح',
      'sort_default': 'الافتراضي',
      'sort_price_asc': 'الأقل سعراً',
      'sort_price_desc': 'الأعلى سعراً',
      'sort_newest': 'الأحدث',
      'sort_name_az': 'أ-ي',
      'sort_name_za': 'ي-أ',
      'view_all': 'عرض الكل',
      'all': 'الكل',
      'quantity': 'الكمية',
      'added_to_cart': 'تمت الإضافة إلى السلة',
      'removed_from_cart': 'تمت الإزالة من السلة',
      'item_removed_from_cart': 'تمت الإزالة من السلة',
      'proceed_to_checkout': 'المتابعة للدفع',
      'order_history': 'سجل الطلبات',
      'order_code': 'رمز طلبك:',
      'reward_points': 'نقاط المكافآت',
      'two_factor_auth': 'التحقق بخطوتين',
      'change_password': 'تغيير كلمة المرور',
      'set_new_password': 'تعيين كلمة مرور جديدة',
      'current_password': 'كلمة المرور الحالية',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_new_password': 'تأكيد كلمة المرور الجديدة',
      'password_updated': 'تم تحديث كلمة المرور بنجاح',
      'active_sessions': 'الجلسات النشطة',
      'security_tips': 'نصائح للحفاظ على أمان حسابك',
      'security_settings': 'إعدادات الأمان',
      'tip_strong_password': 'استخدم كلمة مرور قوية وفريدة',
      'tip_enable_2fa': 'فعّل التحقق بخطوتين',
      'tip_review_sessions': 'راجع الجلسات النشطة بانتظام',
      'english': 'English',
      'arabic': 'العربية',
      'browse': 'تصفح',
      'logout': 'تسجيل الخروج',
      'logout_confirm_title': 'تسجيل الخروج',
      'are_you_sure_logout': 'هل أنت متأكد من تسجيل الخروج؟',
      'logout_successful': 'تم تسجيل الخروج بنجاح',
      'top_categories': 'أفضل التصنيفات',
      'top_seller_products': 'الأكثر مبيعاً',
      'category_mobile_accessories': 'اكسسوارات الموبايل',
      'category_watches': 'ساعات',
      'category_mens_shirts': 'قمصان رجالي',
      'category_mens_shoes': 'أحذية رجالي',
      'category_mens_watches': 'ساعات رجالي',
      'category_laptops': 'لابتوب',
      'category_kitchen_accessories': 'اكسسوارات المطبخ',
      'category_home_decoration': 'ديكور المنزل',
      'category_furniture': 'أثاث',
      'category_beauty': 'تجميل',
      'category_fragrances': 'عطور',
      'category_groceries': 'بقالة',
      'category_smartphones': 'هواتف ذكية',
      'category_clothing': 'ملابس',
      'category_automotive': 'سيارات',
      'category_skincare': 'العناية بالبشرة',
      'category_sports': 'رياضة',
      'category_toys': 'ألعاب',
      'category_books': 'كتب',
      'my_favourites': 'مفضلتي',
      'out_of_stock': 'غير متوفر',
      'notify_when_available': 'إشعار عند التوفر',
      'product_not_found': 'المنتج غير موجود',
      'my_cart': 'سلتي',
      'no_products_found': 'لا توجد منتجات',
      'could_not_load_products': 'تعذر تحميل المنتجات',
      'retry': 'إعادة المحاولة',
      'category': 'التصنيفات',
      'all_categories': 'كل الفئات',
      'date': 'التاريخ',
      'name': 'الاسم',
      'back': 'رجوع',
      'old_price': 'السعر القديم',
      'yes': 'نعم',
      'no': 'لا',
      'description': 'الوصف',
      'popular': 'شائع',
      'top_seller': 'الأكثر مبيعاً',
      'explore': 'استكشاف',
      'developed_by': 'طور بواسطة MahmoudFahmy \u00a9 2023',
      'guest': 'زائر',
      'special_offer': 'عرض خاص',
      'up_to_off': 'خصم يصل إلى %',
      'shop_now': 'تسوق الآن',
      'lets_go': 'هيا بنا',
      'get_special_discount': 'احصل على خصم خاص\n',
      'offer_up_to': 'يصل إلى  ',
      'no_notifications_yet': 'لا توجد إشعارات',
      'mark_read': 'تم القراءة',
      'driver_location': 'موقع السائق',
      'deliverd': 'تم التوصيل',
      'processing': 'قيد المعالجة',
      'canceled': 'ملغي',
      'no_orders_yet': 'لا توجد طلبات بعد',
      'no_orders_hint': 'ستظهر طلباتك هنا بعد إتمام الشراء',
      'detail': 'تفاصيل',
      'total_amount': 'المبلغ الإجمالي:  ',
      'order_no': 'رقم الطلب',
      'email_address': 'البريد الإلكتروني',
      'edit_your_personal_details': 'تعديل بياناتك الشخصية',
      'profile_updated_successfully': 'تم تحديث الملف الشخصي بنجاح',
      'name_required': 'الاسم مطلوب',
      'valid_email_required': 'بريد إلكتروني صحيح مطلوب',
      'email_already_in_use': 'هذا البريد مستخدم بالفعل من حساب آخر',
      'phone_already_in_use': 'هذا الرقم مستخدم بالفعل من حساب آخر',
      'verification_email_sent': 'تم إرسال بريد التحقق إلى {email}. يرجى مراجعة صندوق الوارد لتأكيد التغيير.',
      'success': 'تم بنجاح!',
      'order_will_be_delivered': 'سيتم توصيل طلبك قريباً.\n',
      'thank_you': 'شكراً لاختيارك تطبيقنا!',
      'track_your_orders': 'تتبع طلباتك',
      'back_to_home': 'العودة للرئيسية',
      'unknown_error': 'خطأ غير معروف، يرجى المحاولة لاحقاً',
      'share_feature_coming_soon': 'ميزة المشاركة قريباً',
      'order_subtotal': 'المجموع الفرعي للطلب:',
      'discount_percent': 'الخصم (%d%%):',
      'total_colon': 'الإجمالي:',
      'something_error': 'حدث خطأ',
      'error': 'خطأ',
      'registration_failed': 'فشل التسجيل',
      'create_account': 'إنشاء حساب',
      'create_account_subtitle': 'أنشئ حسابك للبدء.',
      'sign_up_as': 'سجل كـ:',
      'first_name': 'الاسم الأول',
      'last_name': 'الاسم الأخير',
      'first_name_required': 'الاسم الأول مطلوب',
      'last_name_required': 'الاسم الأخير مطلوب',
      'name_must_be_more_than_2': 'يجب أن يكون الاسم أكثر من حرفين',
      'enter_first_name': 'أدخل اسمك الأول',
      'enter_last_name': 'أدخل اسمك الأخير',
      'please_enter_email': 'يرجى إدخال بريد إلكتروني',
      'please_enter_valid_email': 'يرجى إدخال بريد إلكتروني صحيح',
      'enter_email': 'أدخل بريدك الإلكتروني',
      'enter_full_name': 'أدخل اسمك الكامل',
      'phone_number_optional': 'رقم الهاتف (اختياري)',
      'enter_phone': 'أدخل رقم هاتفك',
      'address': 'العنوان',
      'address_required': 'العنوان مطلوب',
      'address_detailed': 'يجب أن يكون العنوان أكثر دقة وتفصيلاً',
      'enter_address': 'أدخل عنوانك',
      'postal_code': 'الرمز البريدي',
      'enter_postal_code': 'أدخل الرمز البريدي',
      'password_required': 'كلمة المرور مطلوبة',
      'password_requirements': 'يجب أن تكون 6 أحرف على الأقل',
      'password_min_length': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
      'update_password': 'تحديث كلمة المرور',
      'password_complexity':
          'يجب أن تحتوي كلمة المرور على حروف كبيرة وصغيرة وأرقام ورموز',
      'password_strength': 'قوة كلمة المرور',
      'password_weak': 'ضعيفة',
      'password_medium': 'متوسطة',
      'password_strong': 'قوية',
      'show_password': 'إظهار كلمة المرور',
      'hide_password': 'إخفاء كلمة المرور',
      'remember_me': 'تذكرني',
      'postal_required': 'الرمز البريدي مطلوب',
      'postal_invalid': 'أدخل رمزًا بريديًا صحيحًا',
      'enter_password': 'أدخل كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'confirm_your_password': 'تأكيد كلمة المرور',
      'please_confirm_password': 'يرجى تأكيد كلمة المرور',
      'passwords_do_not_match': 'كلمات المرور غير متطابقة',
      'empty': 'فارغ',
      'not_match': 'غير متطابق',
      'enter_confirm_password': 'أدخل تأكيد كلمة المرور',
      'i_already_have_account': 'لدي حساب بالفعل!',
      'i_agree_terms': 'أوافق على شروط الخدمة وسياسة الخصوصية',
      'please_agree_terms': 'يرجى الموافقة على شروط الخدمة',
      'already_have_account': 'لديك حساب بالفعل؟ ',
      'register': 'تسجيل',
      'creating_account': 'جاري إنشاء الحساب...',
      'username': 'اسم المستخدم',
      'enter_username': 'أدخل اسم المستخدم',
      'username_required': 'اسم المستخدم مطلوب',
      'username_min_length': 'يجب أن يكون اسم المستخدم 3 أحرف على الأقل',
      'forgot_password': 'نسيت كلمة المرور؟',
      'forgot_password_title': 'نسيت كلمة المرور!',
      'forgot_password_subtitle':
          'لا تقلق! يحدث. يرجى إدخال رقم الهاتف وسنرسل رمز التحقق.',
      'enter_phone_number': 'أدخل رقم الهاتف',
      'continue_btn': 'متابعة',
      'verification': 'التحقق',
      'otp_verification': 'التحقق بالرمز',
      'enter_otp': 'أدخل الرقم المرسل إلى ',
      'dont_receive_code': 'لم تستلم الرمز؟ ',
      'resend': 'إعادة إرسال',
      'submit': 'إرسال',
      'password_update_success': 'تم تحديث كلمة المرور\nبنجاح',
      'password_updated_message': 'تم تحديث كلمة المرور\nبنجاح',
      'sec': ' ثانية',
      'reset_password': 'إعادة تعيين كلمة المرور',
      'reset_password_subtitle':
          'أدخل بريدك الإلكتروني وسنرسل رابط إعادة تعيين كلمة المرور.',
      'send_reset_link': 'إرسال رابط إعادة التعيين',
      'remember_password': 'تذكرت كلمة المرور؟ ',
      'login': 'تسجيل الدخول',
      'check_inbox': 'يرجى التحقق من بريدك الوارد والبريد المزعج.',
      'failed_send_reset': 'فشل إرسال رابط إعادة التعيين',
      'signing_in': 'جاري تسجيل الدخول...',
      'email_or_password_incorrect':
          'البريد الإلكتروني أو كلمة المرور غير صحيحة',
      'welcome_back_title': 'مرحباً بعودتك!',
      'welcome_back_subtitle': 'مرحباً بعودتك، لقد اشتقنا لك',
      'first_time_here': 'هل هذه أول مرة؟ ',
      'signup': 'تسجيل ',
      'or_continue_with': 'أو المتابعة عبر',
      'google': 'Google',
      'apple': 'Apple',
      'welcome_to_shopease': 'مرحباً بك في ShopEase',
      'discover_best_products': 'اكتشف أفضل المنتجات مع توصيل سريع وموثوق.',
      'by_continuing_agree':
          'بالمتابعة، أنت توافق على شروط الخدمة وسياسة الخصوصية',
      'shop': 'تسوق',
      'ease': 'سهل',
      'your_delivery_partner': 'شريك التوصيل الخاص بك',
      'welcome_back': 'مرحباً بعودتك',
      'sign_in_to_continue': 'سجل الدخول للمتابعة',
      'fill_details': 'املأ التفاصيل للبدء',
      'payment_successful': 'تم الدفع بنجاح',
      'payment_failed': 'فشل الدفع',
      'press_back_again_exit': 'اضغط مرة أخرى للخروج',
      'pick_location': 'اختر الموقع',
      'tap_map_to_set': 'اضغط على الخريطة لتحديد موقع التوصيل',
      'set_your_location': 'حدد موقعك',
      'save_and_continue': 'حفظ ومتابعة',
      'not_added_anything': 'لم تضف أي شيء بعد',
      'review_count': '(%d تقييم)',
      'login_title': 'تسجيل الدخول',
      'login_subtitle': 'أدخل بيانات الدخول للوصول إلى حسابك',
      'sign_up_user': 'تسجيل مستخدم ',
      'email_required': 'البريد الإلكتروني مطلوب',
      'valid_email': 'أدخل بريداً إلكترونياً صحيحاً',
      'dont_have_account': 'ليس لديك حساب؟ ',
      'password_required_field': 'كلمة المرور مطلوبة',
      'first_name_required_field': 'الاسم الأول مطلوب',
      'app_bar_search': 'بحث',
      'home_drawer': 'الرئيسية',
      'favourites_drawer': 'المفضلة',
      'profile_drawer': 'الملف الشخصي',
      'log_out_drawer': 'تسجيل الخروج',
      'online': 'متصل',
      'today': 'اليوم',
      'connecting_deliveries': 'جاري توصيل الطلبات...',
      'fast_shipping_low_costs': 'شحن سريع بتكاليف\nمنخفضة',
      'exit': 'خروج',
      'driver_management': 'إدارة السائقين',
      'driver_management_soon': 'إدارة السائقين قريباً',
      'edit_user_info': 'تعديل بيانات المستخدم',
      'button_text': 'زر',
      'accepted_orders': 'الطلبات المقبولة',
      'your_state': 'حالتك',
      'order_details': 'تفاصيل الطلب',
      'items': 'المنتجات',
      'product': 'المنتج',
      'order_date': 'تاريخ الطلب',
      'order_status': 'حالة الطلب',
      'cancel_order': 'إلغاء الطلب',
      'cancel_order_confirm': 'هل أنت متأكد من إلغاء هذا الطلب؟',
      'order_cancelled': 'تم إلغاء الطلب بنجاح',
      'yes': 'نعم',
      'no': 'لا',
      'reviews': 'التقييمات',
      'write_review': 'كتابة تقييم',
      'review_hint': 'شارك رأيك في هذا المنتج...',
      'no_reviews_yet': 'لا توجد تقييمات بعد',
      'rate_driver': 'تقييم السائق',
      'driver_rated': 'تم تقييم السائق',
      'chat_with_driver': 'محادثة مع السائق',
      'min_price': 'السعر الأدنى',
      'max_price': 'السعر الأقصى',
      'order_again': 'إعادة الطلب',
      'items_added_to_cart': 'تمت إضافة العناصر إلى السلة',
      'paid': 'مدفوع',
      'cod': 'كاش',
      'ship_link_driver': 'ShipLink - السائق',
      'ship_link_driver_splash': 'شيب لينك للسائقين',
      'driver': 'سائق',
      'welcome_back_captain': 'مرحباً بعودتك أيها الكابتن!',
      'sign_in_to_start': 'سجل الدخول لبدء التوصيل',
      'email_is_required': 'البريد الإلكتروني مطلوب',
      'password_is_required': 'كلمة المرور مطلوبة',
      'forgot_password_q': 'نسيت كلمة المرور؟',
      'dont_have_account_q': 'ليس لديك حساب؟ ',
      'login_driver': 'تسجيل دخول السائق',
      'enter_your_credentials': 'أدخل بيانات الدخول للوصول إلى حسابك',
      'first_time_here_q': 'هل هذه أول مرة؟ ',
      'signup_': 'تسجيل ',
      'create_driver_account': 'إنشاء حساب سائق',
      'fill_details_to_start': 'املأ التفاصيل للبدء',
      'name_is_required': 'الاسم مطلوب',
      'name_min_2_chars': 'يجب أن يكون الاسم أكثر من حرفين',
      'email_is_required_2': 'البريد الإلكتروني مطلوب',
      'invalid_email': 'بريد إلكتروني غير صالح',
      'email_address_2': 'البريد الإلكتروني',
      'phone_11_digits': 'رقم الهاتف يجب أن يكون 11 رقماً',
      'vehicle_information': 'معلومات المركبة',
      'vehicle_type': 'نوع المركبة',
      'select_vehicle_type': 'اختر نوع المركبة',
      'required_field': 'مطلوب',
      'bike_type_hint': 'نوع الدراجة (مثل: جبلية، كهربائية)',
      'vehicle_number': 'رقم المركبة',
      'governorate': 'المحافظة',
      'select_governorate': 'اختر المحافظة',
      'security_section': 'الأمان',
      'password_required_2': 'كلمة المرور مطلوبة',
      'min_6_characters': '6 أحرف على الأقل',
      'already_have_account_q': 'لديك حساب بالفعل؟ ',
      'sign_in_short': 'تسجيل الدخول',
      'driver_registered_success': 'تم تسجيل السائق بنجاح',
      'something_went_wrong': 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
      'hello': 'مرحباً',
      'ready_for_deliveries': 'جاهز للتوصيل',
      'youre_offline': 'أنت غير متصل',
      'offline': 'غير متصل',
      'active': 'نشط',
      'rating': 'التقييم',
      'accepted': 'مقبول',
      'picked_up': 'تم الاستلام',
      'active_delivery': 'توصيل نشط',
      'customer': 'العميل',
      'user_details': 'تفاصيل المستخدم',
      'egp': 'ج.م',
      'mark_picked_up': 'تأكيد الاستلام',
      'mark_shipped': 'تأكيد الشحن',
      'mark_delivered': 'تأكيد التوصيل',
      'available_orders': 'الطلبات المتاحة',
      'map': 'الخريطة',
      'no_orders_available': 'لا توجد طلبات متاحة',
      'check_back_later': 'تحقق لاحقاً لطلبات جديدة',
      'switch_to_orders_tab': 'انتقل إلى تبويب الطلبات للقبول',
      'order': 'طلب',
      'phone_number_label': 'رقم الهاتف : +2',
      'some_error_try_again': 'حدث خطأ يرجى المحاولة مرة أخرى',
      'untrusted_url': 'رابط غير موثوق',
      'no_chats_yet': 'لا توجد محادثات بعد',
      'chat_with_users': 'تواصل مع المستخدمين بعد قبول الطلبات',
      'no_messages_yet': 'لا توجد رسائل بعد',
      'now': 'الآن',
      'minutes_ago': 'د',
      'hours_ago': 'س',
      'days_ago': 'ي',
      'date_format': '{day}/{month}',
      'selected_count': 'محدد',
      'messages_deleted': 'تم حذف الرسائل',
      'delete_failed': 'فشل الحذف',
      'orders_map': 'خريطة الطلبات',
      'you': 'أنت',
      'order_accepted': 'تم قبول الطلب',
      'order_has_been_accepted': 'تم قبول الطلب',
      'view_route': 'عرض المسار',
      'show_route': 'عرض المسار',
      'personal_info': 'المعلومات الشخصية',
      'name_phone_email': 'الاسم، الهاتف، البريد',
      'vehicle_info': 'معلومات المركبة',
      'vehicle_type_number': 'نوع رقم المركبة',
      'bank_account_earnings': 'الحساب البنكي والأرباح',
      'app_preferences': 'تفضيلات التطبيق',
      'help_support': 'المساعدة والدعم',
      'contact_us_faq': 'اتصل بنا، الأسئلة الشائعة',
      'something_went_wrong_short': 'حدث خطأ ما',
      'initials_placeholder': 'م.م',
      'trips': 'رحلات',
      'week': 'الأسبوع',
      'close': 'إغلاق',
      'type': 'النوع',
      'number': 'الرقم',
      'vehicle_info_title': 'معلومات المركبة',
      'payment_title': 'الدفع',
      'today_earnings': 'اليوم',
      'this_week': 'هذا الأسبوع',
      'all_time': 'كل الوقت',
      'status': 'الحالة',
      'status_updated': 'تم تحديث الحالة',
      'logged_out_successfully': 'تم تسجيل الخروج بنجاح',
      'edit_info': 'تعديل المعلومات',
      'enter_your_name': 'أدخل اسمك',
      'save': 'حفظ',
      'logout_successfully': 'تم تسجيل الخروج بنجاح',
      'logout_btn': 'تسجيل خروج',
      'driver_profile': 'الملف الشخصي للسائق',
      'enter_your_name_hint': 'أدخل اسمك',
      'enter_phone_hint': 'أدخل رقم هاتفك',
      'update_info_successfully': 'تم تحديث المعلومات بنجاح',
      'user': 'مستخدم',
      'mon': 'الإثنين',
      'tue': 'الثلاثاء',
      'wed': 'الأربعاء',
      'thu': 'الخميس',
      'fri': 'الجمعة',
      'sat': 'السبت',
      'sun': 'الأحد',
      'orders_tab': 'الطلبات',
      'available': 'متاحة',
      'accepted_tab': 'مقبولة',
      'completed': 'مكتملة',
      'no_available_orders': 'لا توجد طلبات متاحة',
      'try_again_later': 'حاول مرة أخرى',
      'no_accepted_orders': 'لا توجد طلبات مقبولة',
      'no_completed_orders': 'لا توجد طلبات مكتملة بعد',
      'offline_cached_orders': 'غير متصل - عرض الطلبات المخزنة',
      'km': 'كم',
      'away': 'بعيداً',
      'delivery': 'توصيل',
      'distance': 'المسافة',
      'est_time': 'الوقت التقريبي',
      'chat': 'محادثة',
      'navigate': 'تنقل',
      'straight_line_estimate':
          'تقدير الخط المستقيم - افتح خرائط جوجل للمسار الدقيق',
      'min': 'دقيقة',
      'home_bottom': 'الرئيسية',
      'orders_bottom': 'الطلبات',
      'profile_bottom': 'الملف',
      'bike': 'دراجة',
      'motorcycle': 'موتوسيكل',
      'car': 'سيارة',
      'alexandria': 'الإسكندرية',
      'aswan': 'أسوان',
      'asyut': 'أسيوط',
      'beheira': 'البحيرة',
      'beni_suef': 'بني سويف',
      'cairo': 'القاهرة',
      'dakahlia': 'الدقهلية',
      'damietta': 'دمياط',
      'faiyum': 'الفيوم',
      'gharbia': 'الغربية',
      'giza': 'الجيزة',
      'ismailia': 'الإسماعيلية',
      'kafr_el_sheikh': 'كفر الشيخ',
      'luxor': 'الأقصر',
      'matruh': 'مطروح',
      'minya': 'المنيا',
      'monufia': 'المنوفية',
      'new_valley': 'الوادي الجديد',
      'north_sinai': 'شمال سيناء',
      'port_said': 'بورسعيد',
      'qalyubia': 'القليوبية',
      'qena': 'قنا',
      'red_sea': 'البحر الأحمر',
      'sharqia': 'الشرقية',
      'sohag': 'سوهاج',
      'south_sinai': 'جنوب سيناء',
      'suez': 'السويس',
      'captain': 'كابتن',
      'confirm_cancel_order': 'هل أنت متأكد من إلغاء الطلب؟',
      'loading': 'جارٍ التحميل...',
      'error_loading_orders': 'خطأ في تحميل الطلبات',
      'call': 'اتصال',
      'no_driver': 'لا يوجد سائق',
      'driving_directions': 'الاتجاهات',
      'you_have_reached_destination': 'لقد وصلت إلى الوجهة',
      'start_delivery': 'بدء التوصيل',
      'complete_delivery': 'إتمام التوصيل',
      'delivery_confirmed': 'تم تأكيد التوصيل',
      'payment_method': 'طريقة الدفع',
      'cash_on_delivery': 'الدفع عند الاستلام',
      'scan_to_deliver': 'مسح لتأكيد التوصيل',
      'online_payment': 'دفع إلكتروني',
      'customer_details': 'بيانات العميل',
      'notes': 'ملاحظات',
      'no_notes': 'لا توجد ملاحظات',
      'no_notifications': 'لا توجد إشعارات',
      'clear_all': 'مسح الكل',
      'earnings': 'الأرباح',
      'total_earnings': 'إجمالي الأرباح',
      'trips_count': 'عدد الرحلات',
      'completed_trips': 'الرحلات المكتملة',
      'cancelled_trips': 'الرحلات الملغاة',
      'accept': 'قبول',
      'reject': 'رفض',
      'reason': 'السبب',
      'write_reason': 'اكتب السبب...',
      'no_history': 'لا يوجد سجل',
      'filter': 'تصفية',
      'today_short': 'اليوم',
      'yesterday': 'أمس',
      'this_week_short': 'هذا الأسبوع',
      'this_month': 'هذا الشهر',
      'search_orders': 'بحث في الطلبات...',
      'no_results': 'لا توجد نتائج',
      'connection_lost': 'انقطع الاتصال',
      'check_internet': 'تحقق من اتصال الإنترنت',
      'try_again': 'حاول مرة أخرى',
      'password_label': 'كلمة المرور',
      'no_orders_available_driver': 'لا توجد طلبات متاحة',
      'send_message': 'إرسال رسالة',
      'reject_order': 'رفض الطلب',
      'confirm_cancel': 'هل أنت متأكد من الإلغاء؟',
      'week_earnings': 'هذا الأسبوع',
      'all_time_earnings': 'كل الوقت',
      'error_loading': 'خطأ في تحميل البيانات',
      'you_have_arrived': 'لقد وصلت',
      'customer_phone': 'هاتف العميل',
      'pickup_location': 'موقع الاستلام',
      'dropoff_location': 'موقع التوصيل',
      'delivery_fee': 'رسوم التوصيل',
      'no_reviews': 'لا توجد تعليقات',
      'confirm_logout': 'هل أنت متأكد من تسجيل الخروج؟',
      'update_profile': 'تحديث الملف الشخصي',
      'phone_required': 'رقم الهاتف مطلوب',
      'phone_invalid': 'رقم الهاتف يجب أن يكون 10 أرقام على الأقل',
      'order_placed': 'تم الطلب',
      'confirmed': 'تم التأكيد',
      'out_for_delivery': 'خرج للتوصيل',
      'order_progress': 'تقدم الطلب',
      'current_status': 'الحالي',
      'reorder': 'إعادة الطلب',
      'save_for_later': 'احفظ لوقت لاحق',
      'saved_for_later': 'تم الحفظ',
      'move_to_cart': 'نقل إلى السلة',
      'saved_items': 'العناصر المحفوظة',
      'delivery_proof': 'دليل التسليم',
      'open_in_maps': 'فتح في الخرائط',
      'error_unknown': 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
      'error_network': 'خطأ في الشبكة. يرجى التحقق من اتصالك والمحاولة مرة أخرى.',
      'error_timeout': 'انتهت مهلة الاتصال. يرجى المحاولة مرة أخرى.',
      'error_invalid_credentials': 'البريد الإلكتروني أو كلمة المرور غير صحيحة. يرجى التحقق والمحاولة مرة أخرى.',
      'error_email_already_registered': 'هذا البريد الإلكتروني مسجل بالفعل. يرجى تسجيل الدخول أو استخدام بريد آخر.',
      'error_email_not_confirmed': 'يرجى تأكيد بريدك الإلكتروني قبل تسجيل الدخول. تحقق من صندوق الوارد.',
      'error_invalid_email': 'يرجى إدخال بريد إلكتروني صحيح.',
      'error_phone_already_registered': 'رقم الهاتف هذا مسجل بالفعل. يرجى استخدام رقم آخر.',
      'error_user_not_found': 'لا يوجد حساب بهذا البريد الإلكتروني. يرجى إنشاء حساب جديد.',
      'error_rate_limit': 'محاولات كثيرة جداً. يرجى الانتظار قليلاً والمحاولة مرة أخرى.',
      'error_link_expired': 'انتهت صلاحية هذا الرابط. يرجى طلب رابط جديد.',
      'error_weak_password': 'كلمة المرور ضعيفة جداً. استخدم 8 أحرف على الأقل مع أحرف كبيرة وصغيرة وأرقام.',
      'error_same_password': 'كلمة المرور الجديدة يجب أن تختلف عن الحالية.',
      'error_duplicate_entry': 'هذه المعلومات موجودة بالفعل. يرجى استخدام بيانات مختلفة.',
      'error_not_found': 'المعلومات المطلوبة غير موجودة.',
      'error_permission_denied': 'ليس لديك صلاحية للقيام بهذا الإجراء.',
      'error_required_field': 'يرجى ملء جميع الحقول المطلوبة.',
      'error_invalid_value': 'يرجى إدخال قيمة صحيحة.',
      'error_file_not_found': 'الملف غير موجود.',
      'error_file_too_large': 'الملف كبير جداً. يرجى اختيار ملف أصغر.',
      'error_invalid_data': 'بيانات غير صالحة. يرجى المحاولة مرة أخرى.',
      'payment_opened_new_tab': 'تم فتح صفحة الدفع في علامة تبويب جديدة. أكمل الدفع هناك.',
      'failed_download_invoice': 'فشل في تنزيل الفاتورة',
      'no_payment_methods': 'لا توجد طرق دفع',
      'add_card_hint': 'أضف بطاقة للدفع بشكل أسرع',
      'add_card': 'إضافة بطاقة',
      'complete_card_setup': 'أكمل إعداد البطاقة في علامة التبويب الجديدة',
      'failed_card_setup': 'فشل في بدء إعداد البطاقة',
      'set_default': 'تعيين كافتراضي',
      'coming_soon': 'قريباً',
      'payment_network_error': 'خدمة الدفع غير متاحة. تحقق من اتصالك.',
      'admin_login_subtitle': 'سجّل الدخول بصلاحيات الأدمن لإدارة المنصة.',
      'dashboard_overview': 'نظرة عامة',
      'dashboard': 'لوحة التحكم',
      'users': 'المستخدمون',
      'drivers': 'السائقون',
      'orders': 'الطلبات',
      'revenue': 'الإيرادات',
      'activate': 'تفعيل',
      'driver_activated': 'تم تفعيل السائق',
      'driver_details': 'تفاصيل السائق',
      'activate_driver_title': 'تفعيل السائق',
      'activate_driver_confirm': 'هل أنت متأكد من تفعيل هذا السائق؟',
      'sign_out_title': 'تسجيل الخروج',
      'sign_out_confirm': 'هل أنت متأكد من تسجيل الخروج؟',
      'incomplete': 'غير مكتمل',
      'customer': 'العميل',
      'details': 'التفاصيل',
      'order_status': 'حالة الطلب',
      'order_details': 'تفاصيل الطلب',
      'cancel_order_title': 'إلغاء الطلب',
      'cancel_order_confirm': 'هل أنت متأكد من إلغاء هذا الطلب؟ لا يمكن التراجع.',
      'status_updated': 'تم تحديث حالة الطلب',
    },
  };

  String tr(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get t =>
      Localizations.of<AppLocalizations>(this, AppLocalizations) ?? AppLocalizations(const Locale('en'));
}
