CREATE TABLE IF NOT EXISTS stock_watch (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  notified BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(user_id, product_id)
);

ALTER TABLE stock_watch ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own watches" ON stock_watch;
CREATE POLICY "Users can view own watches" ON stock_watch
  FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own watches" ON stock_watch;
CREATE POLICY "Users can insert own watches" ON stock_watch
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own watches" ON stock_watch;
CREATE POLICY "Users can update own watches" ON stock_watch
  FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own watches" ON stock_watch;
CREATE POLICY "Users can delete own watches" ON stock_watch
  FOR DELETE USING (auth.uid() = user_id);


